### ISSUE TITLE
Cluster type label

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1046]
## Stories

_*-As a cluster admin, I want to label clusters based on their type, CAPI or Vintage, in order to use the same alert rules for both CAPI and Vintage clusters by taking their type into consideration.*_

_*-As a cluster admin, I want to label clusters based on their type, CAPI or Vintage, in order to automate the creation of client certificates based on the cluster type.*_

## Background

At the moment, there isn't an easy way to identify if a cluster is CAPI or Vintage.

The configuration of CAPI clusters is slightly different than the Vintage ones, for example, the legacy components are not running on CAPI clusters.
The creation of client certificates is different depending on the cluster type, CAPI or Vintage.

**Comment by nprokopic** [comment]
Should we be able to use CAPI watch-filter label for this purpose? It will be set only on CAPI clusters.

**Comment by alex-dabija** [comment]
Which label do we set exactly for the `watch-filter`?

**Comment by cornelius-keller** [comment]
Questions from @giantswarm/team-rocket 
- would it not be easier to only label the vintage clusters? This way this does not need to be cleaned up once we migrated fully to capi.

**Comment by fiunchinho** [comment]
As @nprokopic mentioned earlier, we already label CAPI clusters on AWS and Azure with the watch filter label `cluster.x-k8s.io/watch-filter: capi`. I also believe we are labeling CAPI clusters with `cluster-apps-operator.giantswarm.io/watching` so that they work with `cluster-apps-operator`. So I'd say we already have a way to know if a `Cluster` is CAPI or not.

**Comment by bavarianbidi** [comment]
we (@giantswarm/team-rocket ) currently don't set the `watch-filter` label on CAPO clusters

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    cluster.giantswarm.io/description: <CLUSTERNAME> mc cluster
    meta.helm.sh/release-name: <CLUSTERNAME>-cluster
    meta.helm.sh/release-namespace: org-giantswarm
  finalizers:
  - cluster.cluster.x-k8s.io
  - operatorkit.giantswarm.io/prometheus-meta-operator-cluster-api-controller
  - operatorkit.giantswarm.io/cluster-apps-operator-cluster-controller
  generation: 2
  labels:
    app: cluster-openstack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.10.1
    application.giantswarm.io/team: rocket
    cluster-apps-operator.giantswarm.io/watching: ""
    cluster.x-k8s.io/cluster-name: <CLUSTERNAME>
    giantswarm.io/cluster: <CLUSTERNAME>
    giantswarm.io/organization: ""
    helm.sh/chart: cluster-openstack-0.10.1
  name: gario
  namespace: org-giantswarm
```

why not setting `cluster.x-k8s.io/cluster-name` as label to identify if it's a CAPI managed cluster or not? This label already exist everywhere as CAPI use this label internally as well.
