### ISSUE TITLE
 RemoteWrite Alerts/Dashboard

### ISSUE THREAD

**Issue by mcbenjemaa** [giantswarm/roadmap#1175]
Towards https://github.com/giantswarm/roadmap/issues/496

### Description

Adding alerts in case remotewrite reconciliation is failing or didn't work for any reason.

### TODO

Find relevant metrics
Build alert.
Create Dashboard for us and customers

- [x] Add alerts stating that remotewrite config was not configured
- [x] Make sure we are alerted if remote_write does not work, e.g: queues being weird (we have one alert already, let's improve it)
- [x] Update relevant docs.

**Comment by mcbenjemaa** [comment]
Discussing with Theo how to proceed, Current ideas:

- Either we copy the secrets in the remotewrite reconciliation loop

- Or we add another field in the remotewrite CR:

```yaml
secrets:
- name: grafana-cloud-basic-auth
  keys:
    username: <Base64>
    password: <Base64> 
```
