### ISSUE TITLE
Remove kube-proxy component which is no longer needed with cilium

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#1362]
With v19 where Cilium is added in place of aws-cni there is no longer a need for kube-proxy. Furthermore deletion of the kube-proxy is not blocked as well by kiam as v19 will include IRSA solution that takes place.

**Comment by whites11** [comment]
There is one cncf test failing.
To replicate the issue, run the following pods:

```
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: default
spec:
  nodeName: ip-10-1-3-134.eu-central-1.compute.internal
  containers:
  - args:
    - netexec
    - --http-port=8080
    - --udp-port=8080
    image: k8s.gcr.io/e2e-test-images/agnhost:2.39
    imagePullPolicy: IfNotPresent
    name: agnhost
    ports:
    - containerPort: 8080
      hostIP: 127.0.0.1
      hostPort: 54323
      name: http
      protocol: TCP
    securityContext:
      allowPrivilegeEscalation: false
  serviceAccount: default
  serviceAccountName: default
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: default
spec:
  nodeName: ip-10-1-3-134.eu-central-1.compute.internal
  containers:
  - args:
    - netexec
    - --http-port=8080
    - --udp-port=8080
    image: k8s.gcr.io/e2e-test-images/agnhost:2.39
    imagePullPolicy: IfNotPresent
    name: agnhost
    ports:
    - containerPort: 8080
      hostIP: 10.1.3.134
      hostPort: 54323
      name: http
      protocol: TCP
    securityContext:
      allowPrivilegeEscalation: false
  serviceAccount: default
  serviceAccountName: default
---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
  namespace: default
spec:
  nodeName: ip-10-1-3-134.eu-central-1.compute.internal
  containers:
  - args:
    - netexec
    - --http-port=8080
    - --udp-port=8080
    image: k8s.gcr.io/e2e-test-images/agnhost:2.39
    imagePullPolicy: IfNotPresent
    name: agnhost
    ports:
    - containerPort: 8080
      hostIP: 10.1.3.134
      hostPort: 54323
      name: http
      protocol: UDP
    securityContext:
      allowPrivilegeEscalation: false
  serviceAccount: default
  serviceAccountName: default
---
apiVersion: v1
kind: Pod
metadata:
  name: e2e-host-exec
  namespace: default
spec:
  nodeName: ip-10-1-3-134.eu-central-1.compute.internal
  hostNetwork: true
  containers:
  - image: k8s.gcr.io/e2e-test-images/agnhost:2.39
    imagePullPolicy: IfNotPresent
    name: agnhost
    securityContext:
      allowPrivilegeEscalation: false
  serviceAccount: default
  serviceAccountName: default
```

then exec into `e2e-host-exec` and run

```
curl -g --connect-timeout 5 --interface 10.1.3.134 http://localhost:54323/hostname
```

this times out and should work
