### ISSUE TITLE
IRSA on CAPA clusters

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1375]
## Story

_*-As a cluster admin, I want to have IAM Roles for Service Accounts (IRSA) running on CAPA clusters in order to simplify authentication and authorization to AWS services by applications.*_

## Background

Some applications need to access AWS services in order to work properly. IRSA simplifies the authentication and authorization of such applications to AWS services by allowing them to just assume roles (of course it's more complicated then that).

One such application is the [aws-network-topology-operator](https://github.com/giantswarm/aws-network-topology-operator).

## Changes

- [ ] Deploy IRSA to CAPA clusters;
- [ ] Make IRSA a default application on CAPA clusters;
- [ ] Ensure IRSA is running also on management clusters;

## Resources

- [Giant Swarm IRSA documentation](https://docs.giantswarm.io/advanced/iam-roles-for-service-accounts/);
- [AWS IRSA documentation](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html).

**Comment by alex-dabija** [comment]
Nick, Vaclav, Nikola and I had a call today to discuss what needs to be done to get IRSA running on CAPA clusters.

Main conclusions from the call:
- both `irsa-operator` and CAPI controllers already generate a service acccount. It's probably easier if `irsa-operator`is able to reuse a service account that already exists. This needs to be investigated and changes in `irsa-operator` are required;
- `kubeadm` is able to wait until all required secrets and configmaps are available. We'll use this behavior as the signal that the CAPI controllers can continue with cluster creation;
- the configmap format needs to be evaluated to see if the key can easily be extracted.

**Comment by njuettner** [comment]
Here's the configmap how it looks like for our Cloudfront information

```bash 
k get cm -n org-namespace clusterid-irsa-cloudfront -o yaml
```
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterid-irsa-cloudfront
  namespace: org-namespace
data:
  arn: REDACTED
  distributionId: REDACTED
  domain: REDACTED
  originAccessIdentityId: REDACTED
```

And the secret looks like this

```bash
k get secret -n org-namespace clusterid-service-account-v2 -o yaml
```
```yaml
apiVersion: v1
data:
  key: REDACTED
  pub: REDACTED
kind: Secret
metadata:
 ...
```
