### ISSUE TITLE
Label resources with responsible team for use with alert rules

### ISSUE THREAD

**Issue by AverageMarcus** [giantswarm/roadmap#1436]
To aid with writing of Prometheus rules we should expose the "responsible team" label onto pods and similar resources so alerts can be built around those defined teams rather than the current process of excluding metrics based on container names (for example).

First step is to have team name added to all relevant places, e.g.:

* Label your chart with the team name https://github.com/giantswarm/prometheus-meta-operator/blob/master/helm/prometheus-meta-operator/Chart.yaml#L8
* Propagate this label in helpers https://github.com/giantswarm/prometheus-meta-operator/blob/master/helm/prometheus-meta-operator/templates/_helpers.tpl#L26
* Label your resources with it [https://github.com/giantswarm/prometheus-meta-operator/blob/e2ce696f4769d5032c12b8[…]92bc677/helm/prometheus-meta-operator/templates/deployment.yaml](https://github.com/giantswarm/prometheus-meta-operator/blob/e2ce696f4769d5032c12b82f7eeb7b88692bc677/helm/prometheus-meta-operator/templates/deployment.yaml#L7)

(Note: This value shouldn't be used as part of the selector labels as team ownership and names can change, selectors cannot)

Once the values are in place, alerts can be set up to filter based on the value of the `label_application_giantswarm_io_team` label on the metric. E.g. 

We could replace the following:
```
    - alert: ManagementClusterContainerIsRestartingTooFrequentlyAWS
      expr: increase(kube_pod_container_status_restarts_total{container=~"aws-admission-controller.*|aws-node.*|aws-operator.*|cluster-operator.*|route53-manager.*"}[1h]) > 6
      for: 5m
      labels:
        area: kaas
        severity: page
        team: phoenix
```
With the more flexible:
```
    - alert: ManagementClusterContainerIsRestartingTooFrequentlyAWS
      expr: increase(kube_pod_container_status_restarts_total{label_application_giantswarm_io_team="phoenix"}[1h]) > 6
      for: 5m
      labels:
        area: kaas
        severity: page
        team: phoenix
```

(as a very basic example, this might not be exactly what we'd need for this specific alert)

Finally, once this is done there's likely to be some edge cases to handle - such as where the provider team would want to be alerted rather than the team responsible for the application.
