### ISSUE TITLE
Investigate and improve AWS Draining process of nodes with respect to the PDBs

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#1473]

**Comment by paurosello** [comment]
Currently with this deployment and a cluster with 2 nodes we can reproduce the issue:

```
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: helloworld
        image: quay.io/giantswarm/helloworld:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 3
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 50Mi
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: helloworld-pdb
spec:
  minAvailable: 4
  selector:
    matchLabels:
      app: helloworld
```
