### ISSUE TITLE
Configurable pod CIDR

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1481]
## Story

_*-As a cluster operator, I want to configure the cluster's pod CIDR in order to ensure that workloads running on the cluster can communicate with systems running in other peered VPCs or onprem networks.*_

## Background

Customers need more control over the IP ranges used by their infrastructure in order to ensure that workloads running in different VPCs or data centers can talk to each other. The source and destination IPs must be part of non-overlapping CIDRs in order to create a TCP connection.

## Remarks

This is already implemented for CAPG and the same settings in `values.yaml` should be used.

## Resources

- [CAPA cluster definition](https://github.com/giantswarm/cluster-aws);
- [CAPA cluster definition values schema](https://github.com/giantswarm/cluster-aws/blob/main/helm/cluster-aws/values.schema.json);

**Comment by alex-dabija** [comment]
The pod CIDR is configurable. Our current default are the following:
```
vpcCIDR: 10.0.0.0/16
serviceCIDR: 172.31.0.0/16
podCIDR: 100.64.0.0/12
```

I created a cluster with the following settings:
```
vpcCIDR: 10.5.0.0/16
serviceCIDR: 172.16.0.0/16
podCIDR: 172.17.0.0/16
```

I applied the following manifests:
```
---
apiVersion: v1
data:
  values: |
    aws: {}
    bastion: {}
    clusterName: alextest04
    controlPlane:
      replicas: 3
    machinePools:
    - instanceType: m5.xlarge
      maxSize: 10
      minSize: 3
      name: machine-pool0
      rootVolumeSizeGB: 300
    network:
      availabilityZoneUsageLimit: 3
      vpcCIDR: 10.5.0.0/16
      serviceCIDR: 172.16.0.0/16
      podCIDR: 172.17.0.0/16
    organization: giantswarm
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    giantswarm.io/cluster: alextest04
  name: alextest04-userconfig
  namespace: org-giantswarm
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
  name: alextest04
  namespace: org-giantswarm
spec:
  catalog: cluster
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: cluster-aws
  namespace: org-giantswarm
  userConfig:
    configMap:
      name: alextest04-userconfig
      namespace: org-giantswarm
  version: 0.10.0
---
apiVersion: v1
data:
  values: |
    clusterName: alextest04
    organization: giantswarm
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    giantswarm.io/cluster: alextest04
  name: alextest04-default-apps-userconfig
  namespace: org-giantswarm
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    giantswarm.io/cluster: alextest04
  name: alextest04-default-apps
  namespace: org-giantswarm
spec:
  catalog: cluster
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: default-apps-aws
  namespace: org-giantswarm
  userConfig:
    configMap:
      name: alextest04-default-apps-userconfig
      namespace: org-giantswarm
  version: 0.5.5
```
