### ISSUE TITLE
Missing customer tags for EBS volumes

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#1556]
We're currently not tagging EBS volumes for customers  properly and had a small discussion on Friday (21.10.22) how to fix this.

#### 1. Extra-tags flag for ebs-csi-controller

`ebs-csi-controller` has an additional flag `--extra-tags=key=value,...` which we can set to add extra tags on EBS volumes.

I quickly tested it and it works for new EBS volumes **but** it doesn't work for existing ones.

One idea would be letting `cluster-operator` update `cluster-values`, adding all labels from `Cluster CR` starting with `tag.giantswarm.io`. It will be picked up be the `aws-ebs-csi-driver` app and injects those into the `ebs-csi-controller`.

We would need to tag the existing EBS volumes manually until we have a new release with a new `cluster-operator`.

#### 2. Storage Class

I figured out since `v1.6.0` `aws-ebs-csi-driver` supports settings tags on the storage class and it already works in existing clusters. The only catch here is that tags need to be added when a storage class is created. Also existing volumes won't get tagged and existing storage classes can't be modified.

Here's an example:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-test
parameters:
  tagSpecification_1: "foo=bar"
  tagSpecification_2: "bar=baz"
...
  encrypted: "true"
  type: gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```

The tag specification is also only picked up by the `ebs-csi-controller` when EBS volumes getting created. However the advantage is you can set your own individual tags per storage class.

#### 3. New app which tags all volumes in a cluster

A different idea was to have new app which runs periodically inside the cluster which fetches all PV's and tags the EBS volumes. The information which tags need to be set would still need to come from the cluster value approach (cluster-operator) but it would guarantee we set the tags to existings EBS volumes.
