### ISSUE TITLE
Redesign cluster-gcp values to be more GitOps friendly

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#1615]
As part of our automatic upgrades journey in CAPO we have learnt that cluster-<provider> chart should structure in such a way that allows overwriting all sections in different levels.

In CAPG chart we have :

```yaml
machineDeployments:
- name: def00
  # The description is the name of the nodepool in GiantSwarm UIs. It's optional.
  # description:
  failureDomain: europe-west3-a
  instanceType: n2-standard-4
  replicas: 1
  rootVolumeSizeGB: 100
  containerdVolumeSizeGB: 100
  kubeletVolumeSizeGB: 100
  customNodeLabels: []
  customNodeTaints: []
```

My proposition would be to restructure it to:

```yaml
machineDeployments:
  def00: #Name machine deployment
    # The description is the name of the nodepool in GiantSwarm UIs. It's optional.
    # description:
    failureDomain: europe-west3-a
    instanceType: n2-standard-4
    replicas: 1
    rootVolumeSizeGB: 100
    containerdVolumeSizeGB: 100
    kubeletVolumeSizeGB: 100
    customNodeLabels: []
    customNodeTaints: []
```

This is something we have done for cluster OpenStack, for your reference check -> https://github.com/giantswarm/cluster-openstack/pull/120/files
