### ISSUE TITLE
kubectl gs template cluster: generated cluster name should be 5 chars long, but is 10 long with GCP

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1677]
Command:

```
kubectl gs template cluster --provider gcp \
  --organization giantswarm --region foobar --gcp-project myproject \
  --gcp-failure-domains foobar-1 --cluster-version foo
```

Output (truncated):

```yaml
apiVersion: v1
data:
  values: |
    clusterName: xaasz5i509
    ...
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    giantswarm.io/cluster: xaasz5i509
  name: xaasz5i509-userconfig
  namespace: org-giantswarm
```

The generated names are "cryptic", and the longer they get, the harder they are to deal with. While 10 is our upper length limit for the name validation, the generated names should be 5 characters long.
