### ISSUE TITLE
CAPA private cluster templating

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1723]
## Stories

_-As a cluster operator, I want to generate the private and proxy enabled cluster definition with `kubectl-gs` in order to follow best practices recommended by Giant Swarm._

_-As a Giant Swarm developer, I want to generate the cluster definition with `kubectl-gs` in order to easily create a private and proxy enabled workload cluster to test my changes._

## Details

Add an optional argument to `kubectl-gs` called `--cluster-type` which allows users to render different types of clusters. The user gets a public cluster if the flag is not specified.

```
$ kubectl gs template cluster --cluster-type private ...
```

Current cluster types (possible values for `--cluster-type`):
- `public`: current behavior. The user gets a public cluster;
- `private`: the user gets a private cluster (**without proxy configuration**). Currently, with CAPA the cluster will not start because there's no way to access the Internet. It will be supported later. This option should not be enabled in `kubectl-gs` until CAPA has support for it. **Do not implement it as part of this story**;
- `proxy-private`: the user gets a private cluster with proxy configuration (already supported by CAPA, see an example definition bellow).

## Requirements

- `kubectl-gs` has the current behavior if `--cluster-enabled` is not specified. It renders a public cluster;
- `kubectl-gs` renders a private proxy enabled cluster if `--cluster-type proxy-private` if set. See definition example bellow;
- `kubectl-gs` requires additional arguments to be passed in if `--cluster-type proxy-private` is set:
  * `--https-proxy`: `HTTPS_PROXY`, `https_proxy` value;
  * `--vpc-cidr`
- `kubectl-gs` allows the user to pass a few optional arguments:
  * `--http-proxy`: `HTTP_PROXY`, `http_proxy` value. Defaults to the value of `--https-proxy` if not specified;
  * `--no-proxy`: `NO_PROXY`, `no_proxy` value.
- `kubectl-gs` will split the value of `--vpc-cidr` into 4 equal blocks and will use the first `X` number of blocks as the value for `network.subnets` in `values.yaml`. `X` is the number of availability zones to be used by the cluster. See definition example bellow;
- `kubectl-gs` will set `network.vpcMode`, `network.apiMode` and `network.dnsMode` to private in `values.yaml`. See definition example bellow;

## Examples

CAPA private cluster definition with proxy configuration (`--cluster-type proxy-enabled`):
```
---
apiVersion: v1
data:
  values: |
    aws:
      region: eu-west-2
      awsClusterRole: default2
    bastion:
      enabled: false
    proxy:
      enabled: true
      http_proxy: "http://internal-a1c90e5331e124481a14fb7ad80ae8eb-1778512673.eu-west-2.elb.amazonaws.com:4000"
      https_proxy: "http://internal-a1c90e5331e124481a14fb7ad80ae8eb-1778512673.eu-west-2.elb.amazonaws.com:4000"
      no_proxy: "test-domain.com"
    clusterName: alextest36
    controlPlane:
      replicas: 1
    machinePools:
    - instanceType: m5.xlarge
      maxSize: 10
      minSize: 3
      name: machine-pool0
      rootVolumeSizeGB: 300
      availabilityZones:
      - eu-west-2a
      - eu-west-2b
      - eu-west-2c
    network:
      vpcCIDR: 10.20.0.0/16
      topologyMode: GiantSwarmManaged
      availabilityZoneUsageLimit: 3
      vpcMode: private
      apiMode: private
      dnsMode: private
      subnets:
      - cidrBlock: 10.20.0.0/18
      - cidrBlock: 10.20.64.0/18
      - cidrBlock: 10.20.128.0/18
    organization: giantswarm
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    giantswarm.io/cluster: alextest36
  name: alextest36-userconfig
  namespace: org-giantswarm
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
  name: alextest36
  namespace: org-giantswarm
spec:
  catalog: cluster
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: cluster-aws
  namespace: org-giantswarm
  userConfig:
    configMap:
      name: alextest36-userconfig
      namespace: org-giantswarm
  version: 0.20.2
---
apiVersion: v1
data:
  values: |
    clusterName: alextest36
    organization: giantswarm
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    giantswarm.io/cluster: alextest36
  name: alextest36-default-apps-userconfig
  namespace: org-giantswarm
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    giantswarm.io/cluster: alextest36
    giantswarm.io/managed-by: cluster
  name: alextest36-default-apps
  namespace: org-giantswarm
spec:
  catalog: cluster
  config:
    configMap:
      name: alextest36-cluster-values
      namespace: org-giantswarm
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: default-apps-aws
  namespace: org-giantswarm
  userConfig:
    configMap:
      name: alextest36-default-apps-userconfig
      namespace: org-giantswarm
  version: 0.12.3
```
