### ISSUE TITLE
Investigate Azure VM Identity

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#1729]
### Motivation
Team Clippy discussed the options for VM Identities when using CAPZ but we are not yet completely confident with what we know. Therefore we need to investigate a bit more on what's the best way for VM identification with capz.

### Todo
- Investigate what we have to do in order to get the best possible and most secure VM identity with capz
-- the document from the concept meeting in https://github.com/giantswarm/giantswarm/issues/24578#issuecomment-1333982649 might help you

### Outcome
- We are confident on how VM identity has to be done within capz.

**Comment by primeroz** [comment]
Example of how to use UA For a capz Workload Cluster

- Create resource group 
  -  `az group create -l westeurope --name fctest1 --tags "owner=francesco@clippy"`
- Create User Assigned Identity inside resource group
  - `az identity create -g fctest1 -n fctest1`
- Assign contributor role to UA identity in resource gorup
  - `az role assignment create --role "Contributor" --assignee-object-id <IDENTITY PRINCIPAL_ID> --scope "/subscriptions/6b1f6e4a-6d0e-4aa4-9a5a-fbaca65a23b3/resourceGroups/fctest1"` 
- Update your `cluster default values` configmap with
```
    vmIdentity:
      type: "UserAssigned"
      userAssignedIdentitiesIds: 
        - "/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RG_NAME>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<IDENTITY_NAME>"
```
