### ISSUE TITLE
Define and setup ESO deployment

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#1768]
- [ ] figure out and implement the deployment mechanism (collections, WCF directly)
- [ ] monitoring
    - [ ] make sure that the configured `ServiceMonitor` is scrapped
    - [ ] provide a dashboard to visualize metrics
    - [ ] define alerting rules
- [ ] refine, add and deploy Kyverno rule that prevents usage of restricted `ServiceAccounts`
- [ ] create necessary user and operator facing docs

**Comment by uvegla** [comment]
@piontec suggested to add the kyverno policy as part of the "package" that installs ESO in `management-clusters-fleet`. This way it is only added to exactly the clusters that has ESO (because Kyverno checks if the CRDs exist or not). This might also imply some dependency between the order of installing the chart and the kyverno policy, but a better approach than what we did so far with e.g. crossplane (templated in kyverno-policies-dx). Currently `tornado` has the policy added directly here: https://github.com/giantswarm/management-clusters-fleet/pull/232/files

**Comment by uvegla** [comment]
FTR Some resources used to run a simple setup for AWS Secret Manager.

```yaml
apiVersion: v1
data:
  access-key: ...
  secret-access-key: ...
  session-token: ...
kind: Secret
metadata:
  name: aws-secret
  namespace: external-secrets
type: Opaque
```

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret
            key: access-key
          secretAccessKeySecretRef:
            name: aws-secret
            key: secret-access-key
          sessionTokenSecretRef:
            name: aws-secret
            key: session-token
```

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-1
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: secretstore
    kind: SecretStore
  target:
    name: external-1
    creationPolicy: Owner
  data:
    - secretKey: foo
      remoteRef:
        key: example-1
        property: foo
    - secretKey: bar
      remoteRef:
        key: example-1
        property: bar
    - secretKey: changed
      remoteRef:
        key: example-1
        property: baz
```

``` yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-2
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: secretstore
    kind: SecretStore
  target:
    name: external-2
    creationPolicy: Owner
  data:
    - secretKey: dummy
      remoteRef:
        key:example-1
        property: foo
```
