### ISSUE TITLE
Make Nodes more resilient

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#1837]
### Motivation

As a k8s-user i would like to have resilient kubernetes worker nodes (as much as possible).

The `kubelet` has multible configuration options/flags which improves the resilience of a worker node.

### Todo

- [ ] Configure the Eviction Thresholds (see 1.)
- [ ] Configure the system reserved compute resources (see 2.)

**1. Eviction Thresholds**

currently we only set (by not defining anything):
```
    "evictionHard": {
      "memory.available": "200Mi"
    },
    "evictionSoft": {
      "memory.available": "500Mi"
```
As only `memory` values are configured, all remaining eviction Values are ignored (xref: [kubelet code](https://github.com/kubernetes/kubernetes/blob/27b7d3cd41a7866d86040b7a83ccf205dd9ad4ec/pkg/kubelet/apis/config/v1beta1/defaults.go#L211-L213))

The [default values](https://github.com/kubernetes/kubernetes/blob/27b7d3cd41a7866d86040b7a83ccf205dd9ad4ec/pkg/kubelet/apis/config/v1beta1/defaults_linux.go#L22-L28) for `evictionHard` are

```
"memory.available":  "100Mi",
"nodefs.available":  "10%",
"nodefs.inodesFree": "5%",
"imagefs.available": "15%",
```

I would recommend to set these values again (via `kubeadmconfigtemplate`)

```yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: quick-start-default-worker-bootstraptemplate
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            eviction-hard: 'nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<15%,memory.available<100Mi'
```

**2. `system-reserved` + `kube-reserved`**

Currently it's possible for a pod to allocate all the resources which are available on a node. The Operatingsystem and some processes/daemons also require some resources. Therefore it's possible to define the number of resources which are required from the core OS components via `--system-reserved=[cpu=100m][,][memory=100Mi][,][ephemeral-storage=1Gi][,][pid=1000]`

This mean, having a 8000 MB Memory Node and reserving 100Mi for system components, the `kubelet` reports only `7900Mi` as allocatable for `pods`.

(xref: [kubelet configuration](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#system-reserved))
