### ISSUE TITLE
Setting configurable kernel settings like TCP keep alive

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#1875]
TCP connections can be established and they remain connected for a certain amount of time. Server or clients can stop the connection whenever they timeout.

Whenever the migration from Classic Load Balancer to Network Load Balancer happens, some new connection reset occurs because of this.

EC2 have a TCP keep alive of 7200 secs (which means that it waits for 2 hours before start sending a probe to mantain the connection alive) where as the Network Load Balancer drops inactive connections in 350 seconds (immutable and by AWS definition).

We need a way to configure a TCP keep alive kernel settings on the EC2 instances smaller than 350 secs and certify there is no harming impact on the cluster internal connections (as they can be established for longer).

**Comment by T-Kukawka** [comment]
In order to achieve this we will need to add the following to `/etc/kubernetes/config/kubelet.yaml`:

```
allowedUnsafeSysctls:
- "net.*"
```


Then on de deployment the kernel parameter can be set via `securityContext` and allow it on the PSP too:
```
      securityContext:
        sysctls:
        - name: net.ipv4.tcp_keepalive_time
          value: "350"
```

**Comment by T-Kukawka** [comment]
After enabling it in kubelet the PSP has to allow it too:

```
  allowedUnsafeSysctls:
  - net.*
```

Then on the Deployment:

```
      securityContext:
        sysctls:
        - name: net.ipv4.tcp_keepalive_time
          value: "350"
```

And voilà:
![Image](https://user-images.githubusercontent.com/1133954/212881322-7f9232e9-ebd3-4b73-915f-25d096a90262.png)
