### ISSUE TITLE
App catalog definition with reference to existing secret

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1909]
No description provided.

**Comment by gianfranco-l** [comment]
reminder for future self: https://github.com/giantswarm/giantswarm/issues/24237#issuecomment-1403246980

**Comment by gianfranco-l** [comment]
@piontec

**Comment by gawertm** [comment]
@gianfranco-l when do you think you can get to this? 
We are thinking, that we could potentially implement this in Rocket also with medium effort

**Comment by piontec** [comment]
@gawertm I don't think we can get to it anytime soon...

@alex-dabija  correct if I'm wrong, but I think we agreed to solve it differently: https://github.com/giantswarm/giantswarm/issues/24237#issuecomment-1402148429

We want to get rid of configs associated with Catalogs in some mid/long-term future, as they are more confusing than helping. Delivering the necessary Secrets with the management-clusters-fleet on the other hand seems really nice, as you can do that safely and right away.

So, should we even still implement this?

**Comment by alex-dabija** [comment]
> @alex-dabija correct if I'm wrong, but I think we agreed to solve it differently: [giantswarm/giantswarm#24237 (comment)](https://github.com/giantswarm/giantswarm/issues/24237#issuecomment-1402148429)

@piontec I'm confused. This issue is for implementing the changes required by point 2 from @erkanerol's [investigation](https://github.com/giantswarm/giantswarm/issues/24237#issuecomment-1401803535), which aligns with point 2 from your [comment](https://github.com/giantswarm/giantswarm/issues/24237#issuecomment-1402148429):
> - `opsctl ensure catalog` will make sure that each Catalog references the Secret configured in `installations` repo

To me, both are the same. Am I missing something? The yaml in the description of this issue is the same one from @erkanerol's investigation.

**Comment by erkanerol** [comment]
@piontec  What I understand from your last comment above, you did get our proposal wrong. 

We will use catalog configuration as we have decided earlier. 

###  Previous Design

In the beginning, we were thinking that we need to update catalog values as below.

```
# cat https://github.com/giantswarm/installations/blob/master/guppy/appcatalog/cluster-appcatalog-values.yaml
appCatalog:
  config:
    configMap:
      values:
        baseDomain: test.gigantic.io
        managementCluster: guppy
        provider: cloud-director
    secret:
      values:
        sensitiveData1: ENC_encrypted_sensitive_data1
        sensitiveData2: ENC_encrypted_sensitive_data2
```

Since these values are in installations repository, we need to 
- encrypt [while creating the manifests](https://github.com/giantswarm/mc-bootstrap/blob/main/scripts/setup-installations-branch.sh#L75)
- decrypt in [while running opsctl ensure catalogs](https://github.com/giantswarm/mc-bootstrap/blob/main/scripts/install-giantswarm-crds-catalogs.sh#L43)

Since it requires encryption/decryption mechanism in opsctl, it seems a bigger change to us.

###  Last Design

We thought that we have already encryption/decryption mechanism for management-clusters-fleet repo. Then
- We can create a secret on management-clusters-fleet as we do for other secrets
- We can reference the secret in the raw app catalog configs in installations repository like this 
```
# cat https://github.com/giantswarm/installations/blob/master/guppy/appcatalog/cluster-appcatalog-values.yaml
appCatalog:
  config:
    configMap:
      values:
        baseDomain: test.gigantic.io
        managementCluster: guppy
        provider: cloud-director
    secretRef: 
       name: cluster-catalog
       namespace: giantswarm
```
- Then we can adapt `opsctl ensure catalog` commands to respect `secretRef` field too to reference a secret directly. 

### Conclusion

At the end of the day, the `Catalog` CR will be the same in both approaches. The only diff is how to configure the cluster in mc-bootstrap and with opsctl. The second approach seems easier to us. 

@piontec Are you OK with this design? If you are OK, I can take this item. Rocket is OK with implementing the whole mechanism.

**Comment by piontec** [comment]
OK, I think I got the scope here wrong. This is not about adding encryption in `opsctl ensure catalogs`, but rather only setting a Secret reference to an existing secret across all catalogs, right? Something like `opsctl ensure catalogs --use-secret=giantswarm/my-secret`, where `my-secret` is delivered by MCF?

If that's the case, I have one concern left: do we need Catalog CRs refrence at all? Like I said, I'd like to see no config/secret support in Catalog CR in the future. Instead, I'm thinking about something like 'cluster-default-config-map': a specific designated CM/Secret which - if present - is injected as `extraConfigs` into every App CR present on a MC.

As such, do see a way to use the Secret delivered in by MCF directly, without first binding it with Catalog CR? If not, it's still fine and we can do this, but this feature goes against our longer-term vision and that's why I'm trying to avoid it.

**Comment by erkanerol** [comment]
We don't have any mechanism to propagate that single secret to all organization namespaces in MC. It is necessary for all cluser-$provider apps in the MC.

**Comment by ljakimczuk** [comment]
My 2 cents, if I get it right, what you want is already possible to do without any changes to the `opsctl`. In fact, event if it wasn't offered already, no changes to the `opsctl` would be necessary as the configuration is handled by the [appcatalog Helm Chart](https://github.com/giantswarm/appcatalog) the `opsctl` uses underneath, but this is just FYI in case you need to change its configuration in the future or see what is offered.

You can already specify the existing secret by setting the `appCatalog.config.secret.managed: false`, and of course specifying the name and namespace of this secret, as you would usually do when creating it from values.

For example, without any changes to what is currently kept in the `installations` repository I get this:

```yaml
helm template . \
-f ~/Projects/github/GiantSwarm/installations/default/appcatalog/cluster-appcatalog-values.yaml \
-f ~/Projects/github/GiantSwarm/installations/guppy/appcatalog/cluster-appcatalog-values.yaml

---
# Source: appcatalog/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "cluster-catalog"
  namespace: "giantswarm"
data:
  values: |
    baseDomain: test.gigantic.io
    managementCluster: guppy
    provider: cloud-director
---
# Source: appcatalog/templates/appcatalog.yaml
apiVersion: "application.giantswarm.io/v1alpha1"
kind: AppCatalog
metadata:
  name: "cluster"
  annotations:
    helm.sh/resource-policy: keep
  labels:
    application.giantswarm.io/catalog-type: "stable"
    application.giantswarm.io/catalog-visibility: "internal"
    app-operator.giantswarm.io/version: "1.0.0"
spec:
  title: "Giant Swarm Cluster Catalog"
  description: "This catalog holds production revisions of helm charts defining clusters and their pre-installed apps."
  logoURL: "/images/repo_icons/giantswarm.png"
  storage:
    type: "helm"
    URL: "https://giantswarm.github.io/cluster-catalog/"
  config:
    configMap:
      name: "cluster-catalog"
      namespace: "giantswarm"
---
# Source: appcatalog/templates/catalog.yaml
apiVersion: "application.giantswarm.io/v1alpha1"
kind: Catalog
metadata:
  name: "cluster"
  namespace: "giantswarm"
  labels:
    application.giantswarm.io/catalog-type: "stable"
    application.giantswarm.io/catalog-visibility: "internal"
spec:
  title: "Giant Swarm Cluster Catalog"
  description: "This catalog holds production revisions of helm charts defining clusters and their pre-installed apps."
  logoURL: "/images/repo_icons/giantswarm.png"
  storage:
    type: helm
    URL: "https://giantswarm.github.io/cluster-catalog/"
  repositories:
    - type: helm
      URL: "https://giantswarm.github.io/cluster-catalog/"
    - type: oci
      URL: "oci://giantswarmpublic.azurecr.io/cluster-catalog/"
  config:
    configMap:
      name: "cluster-catalog"
      namespace: "giantswarm"
```

And when I re-configure the `guppy` catalog values, i.e. [this](https://github.com/giantswarm/installations/blob/master/guppy/appcatalog/cluster-appcatalog-values.yaml) file, like this:

```yaml
appCatalog:
  config:
    configMap:
      values:
        baseDomain: test.gigantic.io
        managementCluster: guppy
        provider: cloud-director
    secret:
      name: my-test-secret
      namespace: my-test-namespace
      managed: false
```

I get this when rendering the Catalog CRs:

```yaml
helm template . \
-f ~/Projects/github/GiantSwarm/installations/default/appcatalog/cluster-appcatalog-values.yaml \
-f ~/Projects/github/GiantSwarm/installations/guppy/appcatalog/cluster-appcatalog-values.yaml
---
# Source: appcatalog/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "cluster-catalog"
  namespace: "giantswarm"
data:
  values: |
    baseDomain: test.gigantic.io
    managementCluster: guppy
    provider: cloud-director
---
# Source: appcatalog/templates/appcatalog.yaml
apiVersion: "application.giantswarm.io/v1alpha1"
kind: AppCatalog
metadata:
  name: "cluster"
  annotations:
    helm.sh/resource-policy: keep
  labels:
    application.giantswarm.io/catalog-type: "stable"
    application.giantswarm.io/catalog-visibility: "internal"
    app-operator.giantswarm.io/version: "1.0.0"
spec:
  title: "Giant Swarm Cluster Catalog"
  description: "This catalog holds production revisions of helm charts defining clusters and their pre-installed apps."
  logoURL: "/images/repo_icons/giantswarm.png"
  storage:
    type: "helm"
    URL: "https://giantswarm.github.io/cluster-catalog/"
  config:
    configMap:
      name: "cluster-catalog"
      namespace: "giantswarm"
    secret:
      name: "my-test-secret"
      namespace: "my-test-namespace"
---
# Source: appcatalog/templates/catalog.yaml
apiVersion: "application.giantswarm.io/v1alpha1"
kind: Catalog
metadata:
  name: "cluster"
  namespace: "giantswarm"
  labels:
    application.giantswarm.io/catalog-type: "stable"
    application.giantswarm.io/catalog-visibility: "internal"
spec:
  title: "Giant Swarm Cluster Catalog"
  description: "This catalog holds production revisions of helm charts defining clusters and their pre-installed apps."
  logoURL: "/images/repo_icons/giantswarm.png"
  storage:
    type: helm
    URL: "https://giantswarm.github.io/cluster-catalog/"
  repositories:
    - type: helm
      URL: "https://giantswarm.github.io/cluster-catalog/"
    - type: oci
      URL: "oci://giantswarmpublic.azurecr.io/cluster-catalog/"
  config:
    configMap:
      name: "cluster-catalog"
      namespace: "giantswarm"
    secret:
      name: "my-test-secret"
      namespace: "my-test-namespace"
```

No Secret is created, but what I specified is referenced. 

@erkanerol @alex-dabija is this what you need?
