### ISSUE TITLE
Enable dex for private clusters, use proxy for outgoing connections

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1953]
On private clusters, Dex must connect to identity providers via a proxy.

## Tasks

- [x] Clarify how dex-app should be configured to use the proxy server
- [x] Test with private workload cluster

**Comment by vvondruska** [comment]
Added new properties in Dex app chart values to make it possible to define the proxy configuration manually: https://github.com/giantswarm/dex-app/pull/247

**Comment by vvondruska** [comment]
Manual proxy configuration has been tested in a workload cluster in Goat and released in v1.32.3

The proxy can be configured in the user values like this:

```yaml
proxy:
  enabled: true
  http_proxy: "https://url-to-proxy:4000"
  https_proxy: "https://url-to-proxy:4000" 
  no_proxy: "172.31.0.0/16" # Kubernetes API IP or IP range
```
