### ISSUE TITLE
Be able to create a AWS cluster via Control Plane API with as little information as possible

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#198]
**Is your feature request related to a problem? Please describe.**

As a user I would like to create clusters via Control Plane API with the bare minimum info required (as I do in Happa).

Now to create cluster via Control Plane API there are lot of required files users must fill. Most of them can be deducted by the context. Example

```
kubectl gs template cluster \
  --master-az="eu-central-1a" \ # can be defaulted to one AZ as it is in happa
  --domain="eu-central-1.aws.cps.vodafone.com" \ # can be deducted by installation info
  --name="NaaP-nonPRD" \ # can be prefilled with a placeholder
  --credential="credential-igjf9x" \   #can be deducted by org name
  --owner="NAAPS" \ Required
  --release="11.4.0" \   #can be talked last active release
  --region="eu-central-1" # can be deducted by installation info
```

**Describe the solution you'd like**

Make those fields on the CR be optional or filled by an admission controller (or another component).

**Describe alternatives you've considered**

Make the defaulting in all clients / UI. (Not scalable)

**Additional context**

**Comment by alex-dabija** [comment]
Steps:
- [ ] evaluate impact on CRDs chemas;
- [ ] implement only for existing optional fields;
- [ ] implement only for existing required fields.

**Comment by snizhana-dynnyk** [comment]
@alex-dabija will sync with Celestials @MartaD to get this aligned for aws and azure

**Comment by anvddriesch** [comment]
As for firecracker, we could add the defaulting of these attributes to the defaulting webhook in `aws-admission-controller`. How I see it at the moment:

already defaulted in the `aws-admission-controller` and can be empty in the CR:
- master-az

not yet defaulted in `aws-admission-controller` but can simply be done from installation info:
- domain
- region

not yet defaulted in `aws-admission-controller` but can simply be done from other CRs:
- release

not defaulted yet and we would have to decide on a pattern:
- name
- credential (as I understand it, the credential is not always the same pattern, or am I wrong?)

**Comment by pipo02mix** [comment]
> credential (as I understand it, the credential is not always the same pattern, or am I wrong?)

Credential depends on org name, so it should be deducted from it. 

For example a cluster that is in org `Phoenix` it will be

```
> kubectl get secret -l giantswarm.io/organization=Phoenix                                            (giantswarm-viking/giantswarm)
NAME                TYPE     DATA   AGE
credential-ku22e7   Opaque   2      29d
```

this credential -> `credential-ku22e7`

**Comment by marians** [comment]
Regarding default cluster and node pool name: Please stick to the pattern already implemented when creating the cluster via the Rest API.

**Cluster**: `Unnamed cluster`
**Node pool:** `Unnamed node pool`

**Comment by anvddriesch** [comment]
That sounds very reasonable. It should be easy to implement these default values :)

**Comment by whites11** [comment]
> @alex-dabija will sync with Celestials @MartaD to get this aligned for aws and azure

@alex-dabija if you need/want to sync about this create a calendar event and invite me.
Please avoid today as I'm on call, but from tomorrow on choose a free timeslot at your leisure

**Comment by alex-dabija** [comment]
> @alex-dabija if you need/want to sync about this create a calendar event and invite me.
> Please avoid today as I'm on call, but from tomorrow on choose a free timeslot at your leisure

Thanks! Meeting invite is sent for tomorrow.

**Comment by anvddriesch** [comment]
In the past days I have added the defaulting of the cluster domain, description(name) and region into the `aws-admission-controller`. The master-az is also defaulted already.
Now I have started working on the defaulting of the credential-secret but it's not that straight forward.

For example, in `anteater` we have clusters in the organization `adidas`:
```
kind: AWSCluster
metadata:
  creationTimestamp: "2020-05-15T11:40:35Z"
  finalizers:
  - operatorkit.giantswarm.io/aws-operator-cluster-controller
  generation: 4
  labels:
    aws-operator.giantswarm.io/version: 9.1.3
    giantswarm.io/cluster: apie1
    giantswarm.io/organization: adidas
```
However, these clusters use the giantswarm credentials:
```
  provider:
    credentialSecret:
      name: credential-default
      namespace: giantswarm
```
and they belong to the organization `giantswarm`
```
  labels:
    app: credentiald
    app.kubernetes.io/managed-by: Helm
    giantswarm.io/managed-by: credentiald
    giantswarm.io/organization: giantswarm
    giantswarm.io/service-type: system
  name: credential-default
  namespace: giantswarm
```
In fact, the organization `adidas` does not seem to have its own credential:
```
kubectl get secret -l giantswarm.io/organization=adidas -A
NAMESPACE   NAME               TYPE     DATA   AGE
apie1       apie1-kubeconfig   Opaque   1      150d
apie2       apie2-kubeconfig   Opaque   1      158d
aud1t       aud1t-kubeconfig   Opaque   1      21d
ceu01       ceu01-kubeconfig   Opaque   1      5d2h
deu01       deu01-kubeconfig   Opaque   1      172d
htq5q       htq5q-kubeconfig   Opaque   1      55d
hype1       hype1-kubeconfig   Opaque   1      72d
jbo5h       jbo5h-kubeconfig   Opaque   1      42d
mh1m5       mh1m5-kubeconfig   Opaque   1      172d
oaut1       oaut1-kubeconfig   Opaque   1      63d
peu01       peu01-kubeconfig   Opaque   1      172d
seu01       seu01-kubeconfig   Opaque   1      172d
```

So this defaulting would fail.
