### ISSUE TITLE
aws-vpc-operator hanging deletion with `Waiting for CAPA to delete load balancer`

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#2028]
```
aws-vpc-operator-7c57d659cc-zxd8c aws-vpc-operator 2023-02-16T12:26:15.179314161+01:00 2023-02-16T11:26:15.179Z	INFO	Started reconciling AWSCluster	{"controller": "awscluster", "controllerGroup": "infrastructure.cluster.x-k8s.io", "controllerKind": "AWSCluster", "AWSCluster": {"name":"andreas33","namespace":"org-giantswarm"}, "namespace": "org-giantswarm", "name": "andreas33", "reconcileID": "a5a99ec5-8339-4cfb-bfd2-5bb17ab394fa", "namespace": "org-giantswarm", "name": "andreas33"}

aws-vpc-operator-7c57d659cc-zxd8c aws-vpc-operator 2023-02-16T12:26:15.180984364+01:00 2023-02-16T11:26:15.180Z	INFO	VPC endpoint is already deleted	{"controller": "awscluster", "controllerGroup": "infrastructure.cluster.x-k8s.io", "controllerKind": "AWSCluster", "AWSCluster": {"name":"andreas33","namespace":"org-giantswarm"}, "namespace": "org-giantswarm", "name": "andreas33", "reconcileID": "a5a99ec5-8339-4cfb-bfd2-5bb17ab394fa"}

aws-vpc-operator-7c57d659cc-zxd8c aws-vpc-operator 2023-02-16T12:26:15.181756697+01:00 2023-02-16T11:26:15.181Z	INFO	Waiting for CAPA to delete load balancer, trying deletion again in a minute	{"controller": "awscluster", "controllerGroup": "infrastructure.cluster.x-k8s.io", "controllerKind": "AWSCluster", "AWSCluster": {"name":"andreas33","namespace":"org-giantswarm"}, "namespace": "org-giantswarm", "name": "andreas33", "reconcileID": "a5a99ec5-8339-4cfb-bfd2-5bb17ab394fa"}

aws-vpc-operator-7c57d659cc-zxd8c aws-vpc-operator 2023-02-16T12:26:15.184430244+01:00 2023-02-16T11:26:15.184Z	INFO	Finished reconciling AWSCluster	{"controller": "awscluster", "controllerGroup": "infrastructure.cluster.x-k8s.io", "controllerKind": "AWSCluster", "AWSCluster": {"name":"andreas33","namespace":"org-giantswarm"}, "namespace": "org-giantswarm", "name": "andreas33", "reconcileID": "a5a99ec5-8339-4cfb-bfd2-5bb17ab394fa", "namespace": "org-giantswarm", "name": "andreas33"}
```

but the `AWSCluster` object didn't change to the expected final state `Deleted`:

```
λ k get -n org-giantswarm AWSCluster/andreas33 -o yaml | ag -B4 loadbalancerr
  - lastTransitionTime: "2023-02-16T11:16:57Z"
    reason: Deleting
    severity: Info
    status: "False"
    type: LoadBalancerReady

λ k get -n org-giantswarm AWSCluster/andreas33 -o yaml | ag -A2 finalizers:
  finalizers:
  - aws-vpc-operator.finalizers.giantswarm.io
  generation: 6
```

Suggestion: also continue deletion once CAPA finalizer is gone, not only if conditions have the expected values (which currently means relying on internal behavior of CAPA + successful persistence).
