### ISSUE TITLE
Promtail deployment POC

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2054]

**Comment by marieroque** [comment]
PR to add `promtail-app` to `observability-bundle` and **disabled** it by default:
https://github.com/giantswarm/observability-bundle/pull/43

**Comment by marieroque** [comment]
To enable `promtail-app` on MC, edit the configmap  `observability-bundle-konfigure`:
```
apiVersion: v1
data:
  configmap-values.yaml: |
    clusterID: gorilla
    organization: giantswarm
    apps:
      promtail-app:
        enabled: true
......
```

**Comment by marieroque** [comment]
PR to enable `promtail-app` on CAPA clusters: https://github.com/giantswarm/default-apps-aws/pull/171

**Comment by TheoBrigitte** [comment]
I see you are actually merging a lot of things here. I would like to remind and point out that the scope of this issue is to prototype our idea. Let's first make sure we can achieve what we want :
- deploy promtail disabled
- enable it
- update its config

Once we know this is possible we should gather and reflect on how we can implement this in a dynamic way, probably via a logging-operator.

**Comment by marieroque** [comment]
=> We reduce the scope to Vintage AWS only

**Comment by primeroz** [comment]
> CAPZ | All MC | TODO


FYI i deployed, by hand, promtail on glippy MC with the help of @hervenicol 

Ideally if i can help i would like to get into CAPZ MC properly so when i rebuild the MC i don't loose it. Let me know if / how i can help

**Comment by marieroque** [comment]
To deploy/undeploy `promtail` on a Vintage WC, we need to:

1. Create a configmap for the WC observability-bundle
```
apiVersion: v1
data:
  values: |
    apps:
      promtail-app:
        enabled: true
kind: ConfigMap
metadata:
  name: t3yw2-observability-bundle-user-values
  namespace: giantswarm
```

2. Reference this configmap in the App CR
```
....
spec:
  catalog: default-test
  userConfig:
    configMap:
      name: t3yw2-observability-bundle-user-values
      namespace: t3yw2
    secret:
      name: ""
      namespace: ""
```

Then `promtail-app` is created on WC-namespace on MC and `promtail` is deployed on the WC.

To disable (undeploy) it, you need to edit the configmap and set `enabled: false`
