### ISSUE TITLE
Generate user values that exclude all app default values

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#2057]
In the context of 

- https://github.com/giantswarm/roadmap/issues/1181

we want to generate user values to (1) display (for the user to copy, download) and (2) submit as user values in cluster creation.

These user values should only include settings that differ from the app defaults.

This requires a cleanup solution with well-defined rules. Without this cleanup, the resulting user values will contain a copy of all app defaults.

## Rationale

We want users to understand the resulting user values payload as the representation of their own customized cluster configuration. It should only include the details the users filled in themselves.

We want users to be able to copy the resulting user values into a GitOps repository, or write scripts passing these values to a CLI for cluster creation. The smaller this payload, the better. The more default values get copied into the user values, the higher the effort of maintaining these values will become. A minimal user values file will ensure the lowest possible maintenance effort. Also, the fewer properties are contained, the less likely it is that a user values will be affected by an incompatible schema change in the future.

**Comment by marians** [comment]
Here is a simple example illustrating the desired behaviour, while excluding many details.

Given the following *App* default values:

```yaml
connectivity:
  bastion:
    enabled: true
    instanceType: Standard_D2s_v5
```

The form would show the checkbox for `/connectivity/bastion/enabled` as checked. The bastion instance type `Standard_D2s_v5` would be selected in the according widget.

The user then *unchecks* the checkbox.

The resulting user values payload would be:

```yaml
connectivity:
  bastion:
    enabled: false
```

Note that there is no value for `/connectivity/bastion/instanceType` in the user values, since the form value equals the default value.

**Comment by marians** [comment]
We discussed whether arrays would need any special treatment, like deep merging of items. However `helm template` does not apply such behaviour, and we must replicate the effect of `helm template` here.

For example, here are some app default values:

```yaml
nodePools:
  - name: md00
    instanceType: Standard_D2s_v5
```

The user modifies the form to show the following `nodePools` items:

```yaml
nodePools:
  - name: np1
  - name: np2
```

The resulting payload should be this, as the entire `nodePools` value (all items) get overwritten:

```yaml
nodePools:
  - name: np1
  - name: np2
```

Another related question here is: would the instanceType default value `Standard_D2s_v5` automatically apply to all `nodePools` items in this case? The answer is *no*.
