### ISSUE TITLE
Missing baseDomain value for irsa-operator when creating an MC with mc-bootstrap

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2076]
In https://github.com/giantswarm/roadmap/issues/2023, we had to manually apply a manifest like this to get started:

```
apiVersion: v1
data:
  values: |
    baseDomain: grizzly.gaws.gigantic.io
kind: ConfigMap
metadata:
  labels:
    giantswarm.io/cluster: grizzly
  name: grizzly-cluster-values
  namespace: org-giantswarm
```

The cluster values do not exist early enough. cluster-apps-operator is not deployed to the kind cluster.
