### ISSUE TITLE
Reduce rolling frequency in all CAPI environment

### ISSUE THREAD

**Issue by bavarianbidi** [giantswarm/roadmap#2224]
**Is your feature request related to a problem? Please describe.**

With the current implementation of `cluster-*`, all kind of nodes (`control-plane`, `worker`) got rolling, even if only the implementation of one kind has changed.

**Describe the solution you'd like**

* remove usage of `app.kubernetes.io/version` label on the relevant places where a `hash` is build

**Describe alternatives you've considered**

**Additional context**

The root-cause for this behavior is the fact, that on all providers, below labels are added in nearly every `spec` within `cluster-*` via `labels.common` helper.

To detect changes in the `spec`, we build a `hash` of the `spec` and reference these on the relevant places.
As `app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}` is also part of the `labels`, every time a new version got applied, the `hash` change and we trigger a rolling update of all existing nodes within a cluster.

* [azure](https://github.com/giantswarm/cluster-azure/blob/main/helm/cluster-azure/templates/_helpers.tpl#L17-L36)
* [gcp](https://github.com/giantswarm/cluster-gcp/blob/a3a3984c032c9c8a457ac334bccd6a0cc70a3d54/helm/cluster-gcp/templates/_helpers.tpl#L17-L36)
* [aws](https://github.com/giantswarm/cluster-aws/blob/e08b01c1cc23c2221a0613ef8c8b3caf3d3c2817/helm/cluster-aws/templates/_helpers.tpl#L17-L37)
* [cloud director](https://github.com/giantswarm/cluster-cloud-director/blob/090dc060425aafc9c6a3cdbd0791aeb30c1b5b9d/helm/cluster-cloud-director/templates/_helpers.tpl#L22-L43)

```yaml
{{- define "labels.common" -}}
{{- include "labels.selector" $ }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
helm.sh/chart: {{ include "chart" . | quote }}
application.giantswarm.io/team: {{ index .Chart.Annotations "application.giantswarm.io/team" | quote }}
{{- end -}}

{{/*
Selector labels
*/}}
{{- define "labels.selector" -}}
app: {{ include "name" . | quote }}
app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
cluster.x-k8s.io/cluster-name: {{ include "resource.default.name" . | quote }}
giantswarm.io/cluster: {{ include "resource.default.name" . | quote }}
giantswarm.io/organization: {{ required "You must provide an existing organization" .Values.metadata.organization | quote }}
{{- end -}}
```
