### ISSUE TITLE
Update datadog to latest version

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2261]
Towards: https://github.com/giantswarm/giantswarm/issues/20045

Customer want to be able to use latest version of the datadog app we maintain.

We are currently 5 version behind 7.40.0 - 7.43.1 https://github.com/DataDog/datadog-agent/blob/main/CHANGELOG.rst
Also we need to keep this up to date, so enabling `renovate` as we do for other app would be a good way to achieve this.

**Comment by hervenicol** [comment]
When talking about [datadog-app](https://github.com/giantswarm/datadog-app) versions, there are 2 things we could update:

* the chart (which is a git-subtree from https://github.com/DataDog/helm-charts/tree/main/charts/datadog with customizations)
* the app version (https://github.com/DataDog/datadog-agent)

For now, let's use renovate to update images in the chart.
If the chart ever becomes incompatible with the latest images, then we will work on migrating to chart dependency.

**Comment by hervenicol** [comment]
Change of plans:
* we switch to chart dependency
* we see with the customer (via the support channel and the AE) to test it
* then dependabot tracks updates

**Comment by marieroque** [comment]
Current datadog resources on customer WC

```
[datadog-chart-upstream]$ k get all -n datadog
NAME                                        READY   STATUS    RESTARTS   AGE
pod/datadog-8jcgk                           3/3     Running   0          30d
pod/datadog-cluster-agent-8dcd5cb9b-r74q6   1/1     Running   0          30d
pod/datadog-d2svs                           3/3     Running   0          30d
pod/datadog-xcsj4                           3/3     Running   0          10d

NAME                                                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/datadog                                      ClusterIP   10.238.161.132   <none>        8125/UDP   316d
service/datadog-cluster-agent                        ClusterIP   10.238.186.49    <none>        5005/TCP   389d
service/datadog-cluster-agent-admission-controller   ClusterIP   10.238.119.97    <none>        443/TCP    283d

NAME                     DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/datadog   3         3         3       3            3           kubernetes.io/os=linux   389d

NAME                                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/datadog-cluster-agent   1/1     1            1           389d
```

**Comment by marieroque** [comment]
Contact to ping when we are ready: https://gigantic.slack.com/archives/C01MP0EL6QK/p1676627794267009

**Comment by marieroque** [comment]
Test of deployment on `gauss` via the App CR:

```
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: datadog
  namespace: marie
spec:
  catalog: giantswarm-playground
  config:
    configMap:
      name: marie-cluster-values
      namespace: marie
  name: datadog
  namespace: datadog
  version: 3.0.0
  kubeConfig:
     inCluster: false
  userConfig:
    configMap:
      name: datadog-user-values
      namespace: marie
```
