### ISSUE TITLE
Ingesting metrics into Mimir

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2266]
Configure our current Prometheus servers to send metrics to Mimir.

This can be achieved via our RemoteWrite CR, see https://docs.giantswarm.io/getting-started/observability/monitoring/prometheus/remotewrite/

**Comment by hervenicol** [comment]
I created this `mimir-remotewrite.yaml`:
```
apiVersion: monitoring.giantswarm.io/v1alpha1
kind: RemoteWrite
metadata:
  labels:
    application.giantswarm.io/team: atlas
  name: mimir
  namespace: mimir
spec:
  clusterSelector: {}
  remoteWrite:
    name: mimir
    queueConfig:
      capacity: 10000
      maxSamplesPerSend: 1000
      minShards: 10
    tlsConfig:
      insecureSkipVerify: false
    url: http://mimir-gateway.mimir.svc/api/v1/push
```

It sends all metrics from all prometheis to the local Mimir.

It's currently rate-limited by Mimir, but that's a matter of Mimir tuning now.
