### ISSUE TITLE
Adjust Loki retention

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2366]
Towards: #311 

Limit Loki data retention to 1 Month.

There are 2 elements to adjust here:

- Object storage policy (S3 bucket policy)
- Loki settings https://grafana.com/docs/loki/latest/operations/storage/retention/#retention-configuration

**Comment by hervenicol** [comment]
Settings to be set on Loki config:
```
loki:
  loki:
    compactor:
      retention_enabled: true
    limits_config:
      retention_period: 744h  # 744d = 31d
```

Settings are set on current `gauss` config, but will be persisted in `config` repo with https://github.com/giantswarm/config/pull/1789

Then, some chunks may be missed on S3, so we should set a higher delay on S3 bucket policy to "garbage collect" remaining data.
