### ISSUE TITLE
Hide verbose managedFields section when displaying apps in kubectl gs

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#237]
In kubectl gs, hide verbose managedFields section when displaying apps.
The field is used by kubectl but is not interesting for users and makes the CRs verbose. https://github.com/kubernetes/kubernetes/issues/90066

Towards EPIC_URL

## User Story

- As a ROLE, I would like FEATURE so that REASON

## Acceptance Criteria

- [ ] Given PRECONDITION when I do ACTION then I should get RESULT

## Dependencies

- [ ] URL - TITLE

## Tasks

- [ ] URL - TITLE

**Comment by rossf7** [comment]
@cokiengchiara @oponder This still drives me crazy but I've started using the kubectl neat plugin https://github.com/itaysk/kubectl-neat which is errrm.... neat 😄 

I would like `kgs get apps` to do this too but could we combine this with https://github.com/giantswarm/giantswarm/issues/13654 and close here?

```
k -n rfjh2 get apps test-infra -o yaml | k neat
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 1.0.0
  name: test-infra
  namespace: rfjh2
spec:
  catalog: control-plane-test-catalog
  config:
    configMap:
      name: rfjh2-cluster-values
      namespace: rfjh2
  kubeConfig:
    context:
      name: rfjh2
    inCluster: false
    secret:
      name: rfjh2-kubeconfig
      namespace: rfjh2
  name: test-infra
  namespace: test-infra
```
