### ISSUE TITLE
Add SLO make target to generate rules

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2429]
Add a `make` target into `sloth-rules` to generate `PrometheusServiceLevel` rules files via the go tooling in place.

**Comment by QuantumEnigmaa** [comment]
Isn't that already the case ? 
We have the following in the makefile : 
```
.PHONY: generate
generate:
	go run main.go
```

**Comment by QuentinBisson** [comment]
How about we add make generate in circleci?

**Comment by QuantumEnigmaa** [comment]
It's already the case :) 
```
jobs:
  check-generated:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            make generate
            git diff --output /dev/null --exit-code helm/ || (echo 'Detected changes in generated files. Please run "make generate" and push again' && exit 1)
workflows:
  package-and-push-chart-on-tag:
    jobs:
      - check-generated:
          filters:
            tags:
              only: /^v.*/
```
