### ISSUE TITLE
Velero backup on thunder

### ISSUE THREAD

**Issue by tuladhar** [giantswarm/roadmap#2436]
Patrick requested for velero backup of thunder:
- https://gigantic.slack.com/archives/C5PDDBBDG/p1683188115268159

```
---
apiVersion: velero.io/v1
kind: Backup
metadata:
  labels:
    velero.io/storage-location: default
  name: full-backup-2023-05-04
  namespace: velero
spec:
  csiSnapshotTimeout: 10m0s
  defaultVolumesToFsBackup: false
  hooks: {}
  includedNamespaces:
    - default
    - org-shared-clusters
    - org-tkp-onboarding
  includedResources:
    - appregistrations
    - gitlabprojects
    - gitlabprojectaccesstokens
    - harborproject
    - harborprojectmember
    - harborprojectrobotaccount
    - secrets
  metadata: {}
  snapshotVolumes: false
  storageLocation: default
  ttl: 1440h0m0s
```
