### ISSUE TITLE
"Import" existing EKS/AKS clusters

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2485]

**Comment by nce** [comment]
## prerequisites for aws
1. setup aws-cli (optional) & install eksctl
whatever your config might be; For `aws/eksctl`: Assume role of something like this `arn:aws:sts::2xxxx0:assumed-role/GiantSwarmXXXXn/ulli@giantswarm.io`

Check your config:
```
(gs-snail)  ❯❯❯ aws-vault exec gs-snail                                                                                                                                                                                                            
Enter MFA code for arn:aws:iam::08xxxxx84:mfa/iphone13: 2xxxx8
(gs-snail)  ❯❯❯ aws sts get-caller-identity                                                                   
{
    "UserId": "AROATXXXXXJS2MAU:ulli@giantswarm.io",
    "Account": "2xxxxxxx0",
    "Arn": "arn:aws:sts::2xxxxx0:assumed-role/GiantSwarmAdmin/ulli@giantswarm.io"
}
```

2. Create a demo `EKS` cluster
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sample-customer
  region: eu-central-1

managedNodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 0
```
`$ eksctl create cluster -f eks-simple.yaml`

## DRAFT: integration steps
*Assumption: Customer is called `sample`*
### Create customer `Organization`
```
(gs-snail) ❯❯❯ k gs template organization --name sample --output "sample-organization.yaml"
(gs-snail) ❯❯❯ k apply -f sample-organization.yaml
```
