### ISSUE TITLE
Setup prometheus-rules in Mimir

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2521]
Mimir currently runs on `gauss` and do ingest metrics from other Prometheus servers (https://github.com/giantswarm/roadmap/issues/2266 https://github.com/giantswarm/roadmap/issues/2265).

In order to replace the current Prometheus setup we need to move the [Prometheus Rules](https://github.com/giantswarm/prometheus-rules) evaluation from Prometheus Server to Mimir.

**Comment by whites11** [comment]
prometheus-operator does not support mimir, we need to check grafana-operator

**Comment by QuentinBisson** [comment]
The grafana agents supports that out of the box https://gigantic.slack.com/archives/C05AUBA75Q9/p1685709315899309

**Comment by TheoBrigitte** [comment]
We know grafana-agent supports this and we now have an app for it.
What's the next step here ?

**Comment by QuentinBisson** [comment]
Review this https://github.com/giantswarm/grafana-agent-app/pull/3, release and deploy it on gauss

**Comment by TheoBrigitte** [comment]
Also related https://github.com/giantswarm/prometheus-meta-operator/pull/1309

**Comment by QuentinBisson** [comment]
Prometheus Rules are setup in mimir thanks to the grafana agent in flow mode (currently deployed by hand) using the following command:

`helm install grafana-agent grafana/grafana-agent -n monitoring -f configmap.yaml`

with configmap.yaml being:

```yaml
agent:
  configMap:
    content: |
      mimir.rules.kubernetes "local" {
        address = "http://mimir-ruler.mimir.svc:8080/"
      }
controller: deployment # defaults to daemonset which is not useful for our use case
```

That way, prometheus rules CR are transformed by the grafana agent to prometheus rules sent to the mimir ruler.

In addition, we deployed the mimir alertmanager and a datasource to make sure we can see the alerts.

![image](https://github.com/giantswarm/roadmap/assets/2787548/6279e890-ef25-4e72-ad9c-c2ac1f5a7b4a)

What's left:

- [ ] Deploy the grafana agent in a proper way in Gauss instead of manually.
- [ ] Find how to send the alertmanager config to alertmanager?

Questions: 
- Does inhibition rules work in Mimir?
- How to load alertmanager config per tenant?
