### ISSUE TITLE
Learn how to deploy Loki with MCB

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2554]
[MCB](https://github.com/giantswarm/management-cluster-bases) (ask team-honeybadger)

**Comment by hervenicol** [comment]
## What we did:

* Create a MCB branch for you WIP
* Create a GMC branch, with changes in a test install:
     * `kustomization` file (management-clusters/gauss/kustomization.yaml) pointing to your MCB branch
     * A `patch` file with these contents:
```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: management-clusters-fleet
  namespace: flux-giantswarm
spec:
  ref:
	branch: lokigauss
  secretRef:
	name: giantswarm-clusters-ssh-credentials
  url: ssh://[git@ssh.github.com](mailto:git@ssh.github.com):443/giantswarm/giantswarm-management-clusters.git
```
     * A link to this patch file in the kustomization file


* Do your changes in MCB
* Switch to the GMC branch: `k edit gitrepo -n flux-giantswarm management-clusters-fleet` and change .spec.ref.branch
OR `flux0.41.2 create source git -n=flux-giantswarm management-clusters-fleet --branch lokigauss`

## Blocked:
Stopped because we need some templating, like to have dynamic ingress name with install name, aws region… ?
