### ISSUE TITLE
Representation of Catalog Entries (Apps) within the Control Plane

### ISSUE THREAD

**Issue by puja108** [giantswarm/roadmap#26]
Mon, Mar 23, '20 status in this story: https://github.com/giantswarm/roadmap/issues/95
Wed, Apr 8, '20 [Spec: Representation of apps in the CP](https://www.dropbox.com/scl/fi/vo6a6x89k5vuediy91q43/Application-metadata-for-app-catalog-entries.paper?dl=0&rlkey=n1t51gtt2w4ae2exqzix2ddni)
Mon, Apr 20, '20 update: When spec is done, team needs a call to spec out implementation.

## User Story

This is an internal story to solve for several internal technical needs and requirements of user facing stories.

This is the basis. The user stories depending on this are:

- Listing of Apps
- Updating of Apps (update events/notifications)
- Defaulting of App CR fields (user just says I want prometheus and we default to latest version)
- Validation of App CRs (specifically validate if app name and version are exisiting in said catalog)

Latter 2 stories are concerned with havng functionality baked into our Control Plane and its Kubernetes API so that we are not dependent on the to-be-deprecated GS API.

Future stories depending on this might be:

- Dependency management between apps and other apps
- Dependency management between apps and GS versions
- Making required config fields explicit
- Other metadata to apps (Screenshots, long descriptions, example configs)

## Current State

Currently, an App Catalog is represented solely by its appcatalog CR in the CP. There's no information about its contents in the CP.

Happa talks directly to the storage of the Helm repository depicted in the appcatalog CR (i.e. in our cases Github) to get the `index.yaml`, parse it, and use it for some defaulting and representation cases.

The functionality to list apps is not present in our API. Thus, UX is being able to see the SSoT, i.e. Github, and following it to check out which apps are present.

## Requirements

What we need is a way to get the SSoT, i.e. a list of apps, their versions, as well as metadata, from a definite place inside the Control Plane.

## Options

As we are extending the Kubernetes API of the CP there's basically 2 ways that are native:

1. CRD + Controller (i.e. Operator Pattern)
2. Microservice that offers an aggregated API

While 1 has been our goto solution for most issues, we often have mitigated the impact of such an asynchronous, event-driven API towards the user by adding a microservice or API logic of our own. Latter patterns we want to get rid of as our API and the microservices that "translate" towards CRDs are something we want to deprecate mid-term.

For 2 we do not have any production experience. It is used upstream for the metrics API and Team Ludacris is considering using it for giantswarm/roadmap#13 (Health of TCs). There's a PoC that they have built in the Hackathon last week.

Team Batman has extensively evaluated Option 1 (see also https://docs.google.com/document/d/1LCd4XeLh8fYKILjTfyvBILrWZc07Gn0zdrbpC-MZUOg/edit), so we will describe this and also a lower fidelity spec of Option 2 in the following.

Keep in mind that no matter what option we go with the SSoT stays within the Helm Repository, no matter if that repository is blob storage with an `index.yaml` like right now, or might have a better API that can offer such information as in chart-museum and Harbor. Currently, I do not see a way around having a local representation somehow (more on this in the harbor case below). Correct me if this assumption is wrong.

### 1) AppCatalogEntry CRD

The idea is to have a cluster-scoped `AppCatalogEntry` CR per App in a Catalog. This CR is to be created by a new controller in `app-operator` based on the SSoT that is the appCatalog storage, i.e. github or other helm repo and its `index.yaml`

Sample CR (details can be discussed in apiextensions PR once we have a better plan here)

```
metadata:
  name: kong-incubator
  labels:
   application.giantswarm.io/catalog: giantswarm-incubator
spec:
  name: kong-app
  description: The Cloud-Native Ingress and Service Mesh for APIs and Microservices
  engine: gotpl
  home: https://KongHQ.com/
  Icon: https://s3.amazonaws.com/downloads.kong/universe/assets/icon-kong-inc-large.png
  sources:
    - https://github.com/Kong/kong
  urls:
    - https://giantswarm.github.com/giantswarm-incubator-catalog/kong-app-0.2.0.tgz
versions:
  - version: 0.2.1
    appVersion: 1.2.3
    created: "2019-09-28T13:18:25.002458784Z"
  - version: 0.2.0
    appVersion: 1.2.2
    created: "2019-08-28T13:18:22.004458784Z"
```

This CRD can then be used for all possible use cases mentioned above. It can be extended to include additional metadata with time, but the idea would be to start small.

### 2) appcatalog-service

A microservice serving an aggregated API that does one of the 2 following things:

1. In case of blob storage for Helm Repository, it downloads the `index.yaml`, keeps a purged representation of that in its "cache" and answers requests for apps, versions, and metadata.
2. In case of chart-museum/harbor it proxies (and maybe caches) requests to said chart registry.

The reason for a proxy in case 2 is that it abstracts away from the actual representation and storage in case those change. Another reason is that for a better UX a single place to get the information about app and version availability and install would make more sense. Having the user switch to a Chart Registry frontend to explore which apps they want and then come back and install and configure them in clusters sounds icky. Again correct me if I'm wrong.
