### ISSUE TITLE
Implementation: Delete of a private cluster is not clean and leaves the MC cluster in a not ready state

### ISSUE THREAD

**Issue by primeroz** [giantswarm/roadmap#2620]
## Motivation

When a `private WC cluster` is deleted the cleanup , on the `MC AzureCluster` resource, is not _clean / complete_ and the MC cluster is left in an unready state

After the cluster is deleted ( and all resources including the private endpoint are gone ) 

* glippy azurecluster status is not ready
```
➜ kubectl get -n org-giantswarm azurecluster glippy -o yaml | yq '.status.conditions[] | select(.type=="Ready")'  
lastTransitionTime: "2023-06-28T13:35:56Z"
message: privateendpoints creating or updating
reason: Creating
severity: Info
status: "False"
type: Ready
```

* glippy has a `leftover` longrunningOperation`
```
 λ kubectl -n org-giantswarm get azurecluster glippy -o yaml | yq .status.longRunningOperationStates
- data: eyJtZXRob2QiOiJERUxFVEUiLCJwb2xsaW5nTWV0aG9kIjoiQXN5bmNPcGVyYXRpb24iLCJwb2xsaW5nVVJJIjoiaHR0cHM6Ly9tYW5hZ2VtZW50LmF6dXJlLmNvbS9zdWJzY3JpcHRpb25zLzZiMWY2ZTRhLTZkMGUtNGFhNC05YTVhLWZiYWNhNjVhMjNiMy9wcm92aWRlcnMvTWljcm9zb2Z0Lk5ldHdvcmsvbG9jYXRpb25zL3dlc3RldXJvcGUvb3BlcmF0aW9ucy8zN2MyNGQxNC05YjU2LTQ2M2UtYTA2YS00YWYzNzRiZjI1MTg_YXBpLXZlcnNpb249MjAyMi0wNS0wMSIsImxyb1N0YXRlIjoiSW5Qcm9ncmVzcyIsInJlc3VsdFVSSSI6Imh0dHBzOi8vbWFuYWdlbWVudC5henVyZS5jb20vc3Vic2NyaXB0aW9ucy82YjFmNmU0YS02ZDBlLTRhYTQtOWE1YS1mYmFjYTY1YTIzYjMvcHJvdmlkZXJzL01pY3Jvc29mdC5OZXR3b3JrL2xvY2F0aW9ucy93ZXN0ZXVyb3BlL29wZXJhdGlvblJlc3VsdHMvMzdjMjRkMTQtOWI1Ni00NjNlLWEwNmEtNGFmMzc0YmYyNTE4P2FwaS12ZXJzaW9uPTIwMjItMDUtMDEifQ==
  name: cluster05-api-privatelink-privateendpoint
  resourceGroup: glippy
  serviceName: privateendpoints
  type: DELETE
```

* the `base64 in the data` field has some garbage in it
```
➜ echo eyJtZXRob2QiOiJERUxFVEUiLCJwb2xsaW5nTWV0aG9kIjoiQXN5bmNPcGVyYXRpb24iLCJwb2xsaW5nVVJJIjoiaHR0cHM6Ly9tYW5hZ2VtZW50LmF6dXJlLmNvbS9zdWJzY3JpcHRpb25zLzZiMWY2ZTRhLTZkMGUtNGFhNC05YTVhLWZiYWNhNjVhMjNiMy9wcm92aWRlcnMvTWljcm9zb2Z0Lk5ldHdvcmsvbG9jYXRpb25zL3dlc3RldXJvcGUvb3BlcmF0aW9ucy8zN2MyNGQxNC05YjU2LTQ2M2UtYTA2YS00YWYzNzRiZjI1MTg_YXBpLXZlcnNpb249MjAyMi0wNS0wMSIsImxyb1N0YXRlIjoiSW5Qcm9ncmVzcyIsInJlc3VsdFVSSSI6Imh0dHBzOi8vbWFuYWdlbWVudC5henVyZS5jb20vc3Vic2NyaXB0aW9ucy82YjFmNmU0YS02ZDBlLTRhYTQtOWE1YS1mYmFjYTY1YTIzYjMvcHJvdmlkZXJzL01pY3Jvc29mdC5OZXR3b3JrL2xvY2F0aW9ucy93ZXN0ZXVyb3BlL29wZXJhdGlvblJlc3VsdHMvMzdjMjRkMTQtOWI1Ni00NjNlLWEwNmEtNGFmMzc0YmYyNTE4P2FwaS12ZXJzaW9uPTIwMjItMDUtMDEifQ== | base64 -d

{"method":"DELETE","pollingMethod":"AsyncOperation","pollingURI":"https://management.azure.com/subscriptions/6b1f6e4a-6d0e-4aa4-9a5a-fbaca65a23b3/providers/Microsoft.Network/locations/westeurope/operations/37c24d14-9b56-463e-a06a-4af374bf2518base64: invalid input
```

* deleting the `longrunningoperationstate` does not fix the azurecluster state since the codepath that handles that is not excercized

## ToDo
- [x] Identify the issue
- [x] fix the issue

## Outcome
Deleting private clusters leave a clean state

**Comment by nprokopic** [comment]
Tested fix, it works :) 

Before:

```
  - lastTransitionTime: "2023-07-21T11:37:06Z"
    message: privateendpoints creating or updating
    reason: Creating
    severity: Info
    status: "False"
    type: PrivateEndpointsReady
...
  longRunningOperationStates:
  - data: SOME_STUFF_HERE.......MDUtMDEifQ==
    name: cluster05-api-privatelink-privateendpoint
    resourceGroup: glippy
    serviceName: privateendpoints
    type: DELETE
  - data: SOME_STUFF_HERE.......ZXJzaW9uPTIwMjItMDUtMDEifQ==
    name: np2000-api-privatelink-privateendpoint
    resourceGroup: glippy
    serviceName: privateendpoints
    type: DELETE
  ready: true
```

After (`longRunningOperationStates` field is empty):

```
  - lastTransitionTime: "2023-07-21T12:37:20Z"
    status: "True"
    type: PrivateEndpointsReady
```
