### ISSUE TITLE
cert-manager http solver pods unable to communicate

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#2656]
We encountered this in the newest CAPA release (0.36.2), but a quick check with newest aws vintage release suggested the same problem occurs there as well so it may be an issue for existing production.

#### Settings on the WC:
- oidc settings on the controlplane were enabled
- `ingress` was added to `externalDNS.sources` setting for default external dns app
- `ingress nginx` app installed
- `auth-bundle` app installed in `kube-system` namespace

#### What happened:
When installing the auth-bundle which contain two ingresses for dex and athena, certificates were not issued by cert-manager as expected.
http solver pods spawned but were unable to communicate through network.

from the challenge resource:
```
spec:
  authorizationURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/244937906837
  dnsName: dex.aw33u.gaws.gigantic.io
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-giantswarm
  key: gfbAOZpFNZSU-LgxZsp0uoFra-7XeJhMp103BK4Thsw.ve-upqX7AZqNXrbsPPoQghocDAJ8hZSb0fOG6llFjMw
  solver:
    http01:
      ingress:
        class: nginx
  token: gfbAOZpFNZSU-LgxZsp0uoFra-7XeJhMp103BK4Thsw
  type: HTTP-01
  url: https://acme-v02.api.letsencrypt.org/acme/chall-v3/244937906837/gQTlAg
  wildcard: false
status:
  presented: true
  processing: true
  reason: 'Waiting for HTTP-01 challenge propagation: failed to perform self check
    GET request ''http://dex.aw33u.gaws.gigantic.io/.well-known/acme-challenge/gfbAOZpFNZSU-LgxZsp0uoFra-7XeJhMp103BK4Thsw'':
    Get "http://dex.aw33u.gaws.gigantic.io/.well-known/acme-challenge/gfbAOZpFNZSU-LgxZsp0uoFra-7XeJhMp103BK4Thsw":
    context deadline exceeded (Client.Timeout exceeded while awaiting headers)'
  state: pending
  ```

Resolver pods were unable to receive requests on the IP addresses, which are assigned to them:
```
request: "GET /.well-known/acme-challenge/BNslS15jdhLa9YbLuI5KsY7Q1hHzz1FC6DkWLgneDpQ HTTP/1.0", upstream: "http://100.64.2.45:8089/.well-known/acme-challenge/BNslS15jdhLa9YbLuI5KsY7Q1hHzz1FC6DkWLgneDpQ", host: "athena.rz3s5.gaws.gigantic.io"
```

When the same endpoint was called from another pod running in the cluster, it did not return any response.
```
curl http://100.64.2.45:8089/.well-known/acme-challenge/BNslS15jdhLa9YbLuI5KsY7Q1hHzz1FC6DkWLgneDpQ
curl: (28) Failed to connect to 100.64.2.45 port 8089 after 128398 ms: Couldn't connect to server
```

This seems to be related to default deny-all policy. Applying the following network policy for the specific solver solved the problem.

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: http-solver-network-policy-test
  namespace: kube-system
spec:
  egress:
  - {}
  ingress:
  - ports:
    - port: 8089
      protocol: TCP
  podSelector:
    matchLabels:
      acme.cert-manager.io/http-domain: "2701331137"
      acme.cert-manager.io/http-token: "912068148"
      acme.cert-manager.io/http01-solver: "true"
  policyTypes:
  - Ingress
  - Egress
  ```
#### What we expected
When using the default cert manager with the default giantswarm clusterissuer and our ingress nginx app, certificates for ingresses should be issued.

**Comment by ubergesundheit** [comment]
Tried to recreate the issue today on both vintage (gaia) and capi (gollum) using the following steps:

- create cluster (vintage: 19.0.0, capi: 0.36.2). Included cert-manager-app chart versions are vintage: 2.21.0 and capi 2.23.2
- Install ingress-nginx 2.30.1 via happa
- Create a ingress (with changed domain for vintage and capi)
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: template-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-giantswarm
    kubernetes.io/tls-acme: 'true'
spec:
  ingressClassName: nginx
  rules:
    - host: |-
        doing.cluster-id.gaws.gigantic.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes
                port:
                  name: https
  tls:
    - hosts:
        - doing.cluster-id.gaws.gigantic.io
      secretName: dong-ding
```

Both times cert-manager was able to issue certificates.

From the linked issue (#2657) I see you installed a second ingress controller.
