### ISSUE TITLE
test/release auth bundle app

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#2657]
Expectation is that installing the auth-bundle will result in a kubectl login ready cluster.

Known blocker:
- https://github.com/giantswarm/roadmap/issues/2656 needs to be solved

Known requirements (these need to be default eventually)
- ingress controller with the following setting needs to be installed in the cluster:
```
controller:
  ingressClassResource:
    name: auth
    controllerValue: k8s.io/ingress-nginx-auth
```
- external-dns needs the following setting:
```
externalDNS:
  sources:
  - ingress
```
- cluster-app controlplane settings need the oidc values filled out: https://docs.giantswarm.io/advanced/configure-dex-in-your-cluster/#configure-the-oidc-values-on-the-cluster-resource
