### ISSUE TITLE
Manually create and define `Cluster` CR for the EKS cluster 

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2668]
As some of our apps (like `PrometheusMetaOperator`) rely on CAPI objects to discover target workload clusters, we have to make sure that the imported (and read-only) EKS clusters can be discovered that way as well. As [phoenix figured out](https://github.com/giantswarm/giantswarm/issues/27377#issuecomment-1630350109), we can't get this functionality out of the existing CAPA controllers. As such, we have decided to continue with manual solution for the purpose of PoC. The manual solution means that we will create the needed CAPI objects manually (for the existing EKS cluster) and then uninstall (or scale to 0) operators that might want to act on them.

**Comment by piontec** [comment]
@giantswarm/team-phoenix Can we get your help here, so the manually created CAPI objects make sense and are done by someone, who has experience and knows how they should look like? We can help with deployment/delivery, but it would be cool if you provide the object definition itself.

**Comment by calvix** [comment]
> @giantswarm/team-phoenix Can we get your help here, so the manually created CAPI objects make sense and are done by someone, who has the experience and knows what they should look like? We can help with deployment/delivery, but it would be cool if you provide the object definition itself.

you can use this as a reference
https://github.com/giantswarm/cluster-eks/blob/main/helm/cluster-eks/templates/_cluster.tpl

when the cluster runs it looks like this:( I celan few resources that you should not need) 
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    meta.helm.sh/release-name: vac0eks
    meta.helm.sh/release-namespace: org-giantswarm
  creationTimestamp: "2023-07-20T13:36:17Z"
  labels:
    app: cluster-eks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.3.1
    application.giantswarm.io/team: phoenix
    cluster-apps-operator.giantswarm.io/watching: ""
    cluster.x-k8s.io/cluster-name: vac0eks
    cluster.x-k8s.io/watch-filter: capi
    giantswarm.io/cluster: vac0eks
    giantswarm.io/organization: giantswarm
    giantswarm.io/service-priority: highest
    helm.sh/chart: cluster-eks-0.3.1
  name: vac0eks
  namespace: org-giantswarm
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 100.64.0.0/12
    services:
      cidrBlocks:
      - 172.31.0.0/16
  controlPlaneEndpoint:
    host: 512CCD8E8C2ABC740F547A89B16A91D8.gr7.eu-west-2.eks.amazonaws.com
    port: 443
status:
  controlPlaneReady: true
  failureDomains:
    eu-west-2a:
      controlPlane: true
    eu-west-2b:
      controlPlane: true
    eu-west-2c:
      controlPlane: true
  infrastructureReady: true
  phase: Provisioned
```


I would suggest adding a pause annotation to the `Cluster` CR to ensure no CAPI  components will reconcile it
```
cluster.x-k8s.io/paused: "true"
```

**Comment by piontec** [comment]
CC @nce , we'll have to fill in the data and deploy an object like this... but... 
In a normal situation (fully managed cluster), how does it point to a `kube.config`? Is it generated dynamically just by using the cluster's `controlPlaneEndpoint.host` property?

@giantswarm/team-atlas is an object like this enough for you to test and run ie. `PMO`?

**Comment by T-Kukawka** [comment]
The kubeconfig is generated via opsctl login actually - this is not implemented for the `Managed EKS with CAPI` but implemented for other CAPI providers/Vintage - do not know the technical details tho, can be looked up for sure

**Comment by T-Kukawka** [comment]
But indeed it probably uses the host part: https://github.com/giantswarm/kubectl-gs/blob/main/cmd/login/command.go

**Comment by QuentinBisson** [comment]
@piontec yes we basically need  some labels on the CR, the kube-config and

```yaml
  controlPlaneEndpoint:
    host: 512CCD8E8C2ABC740F547A89B16A91D8.gr7.eu-west-2.eks.amazonaws.com
    port: 443
 ```

We might need some secrets for etcd but let's see later

**Comment by calvix** [comment]
> The kubeconfig is generated via opsctl login actually - this is not implemented for the `Managed EKS with CAPI` but implemented for other CAPI providers/Vintage - do not know the technical details tho, can be looked up for sure

opsctl is only used for the real humans nor  for operators

**Comment by calvix** [comment]
> CC @nce , we'll have to fill in the data and deploy an object like this... but... In a normal situation (fully managed cluster), how does it point to a `kube.config`? Is it generated dynamically just by using the cluster's `controlPlaneEndpoint.host` property?
> 
> @giantswarm/team-atlas is an object like this enough for you to test and run ie. `PMO`?

there is no reference from any CRs to the kubeconfig as that is more like a CAPI provider-specific thing, nevertheless, all  tools and operators expect that a running and working cluster has a secret called `${CLUSTER_ID}-kubeconfig`  in the same namespace as Cluster CR, which is always working kubeconfig that works without any need for some third-party authenticator - so be careful that the kubeconfig do not call tool like ` aws-iam-authenticator`

**Comment by mproffitt** [comment]
Glancing through the comment from the reference ticket https://github.com/giantswarm/giantswarm/issues/27377#issuecomment-1630350109 I think there is no need to write a custom operator to scan EKS resources.

Since version 0.12.0, Crossplane has had `ObserveOnly` resources as an alpha flag to provider controllers (See [original issue here](https://github.com/crossplane/crossplane/issues/1722) and [crossplane documentation here](https://docs.crossplane.io/latest/concepts/managed-resources/#managementpolicy)

My thinking here is that we can use [`upbound/provider-aws-eks:Cluster`](https://doc.crds.dev/github.com/upbound/provider-aws/eks.aws.upbound.io/Cluster/v1beta1) in `ObserveOnly` mode, then patch the necessary fields from `status.atProvider` to a [`crossplane-contrib/provider-kubernetes:Object`](https://doc.crds.dev/github.com/crossplane-contrib/provider-kubernetes/kubernetes.crossplane.io/Object/v1alpha1@v0.9.0#spec-forProvider-manifest) which creates the ClusterCR

To enable crossplane to import the EKS cluster, the XRC would require annotating with `crossplane.io/external-name: EKS_CLUSTER_ID` which for an import from a customer we would have to know anyway.

Additionally by binding [`ClusterAuth`](https://doc.crds.dev/github.com/upbound/provider-aws/eks.aws.upbound.io/ClusterAuth/v1beta1) to the same XRD, also in `ObserveOnly`, we shoud be able to pull back the `kubeconfig` as part of the same import without requiring additional components to search / create this.

**Comment by fiunchinho** [comment]
What does create the [crossplane-contrib/provider-kubernetes:Object](https://doc.crds.dev/github.com/crossplane-contrib/provider-kubernetes/kubernetes.crossplane.io/Object/v1alpha1@v0.9.0#spec-forProvider-manifest)? How would we patch the `status.atProvider` field?

**Comment by mproffitt** [comment]
I'm building a PoC on this at the moment, will have it ready complete for EoD which will help show how this works but:

You don't patch `status.atProvider`. for the Composition, you read from those fields and write back to the `CompositeResource`, then read from the `CompositeResource` to write to the kubernetes `Object`.

Roughly, it would look like this in the Crossplane Composition:

**clusters.eks.aws.upbound.io**

```yaml
patches:
  - type: ToCompositeResource
    fromFieldPath: status.atProvider.endpoint
    toFieldPath: status.endpoint
  - type: ToCompositeResource
    fromFieldPath: status.atProvider.kubernetesNetworkConfig.serviceIpv4Cidr
    toFieldPath: status.serviceCidrBlock
```

I haven't worked with `provider-kubernetes` yet but normally the reverse is then true to read from `status` and load into the object manifest

**objects.kubernetes.crossplane.io**

```yaml
patches:
  - fromFieldPath: status.endpoint
    toFieldPath: spec.forProvider.manifest.spec.controlPlaneEndpoint.host
  - fromFieldPath: status.serviceCidrBlock
    toFieldPath: spec.forProvider.manifest.spec.services.cidrBlocks[0]
```

The idea would be that anything in apigroup `clusters.eks.aws.upbound.io` is completely read-only, we never write back into objects in this group. The same is true for `clusterauth`
