### ISSUE TITLE
Sane defaults for `linkerd-viz`

### ISSUE THREAD

**Issue by mcharriere** [giantswarm/roadmap#2703]
The app doesn't have good defaults to be run in production:

- resources are not set in general
- tap is running only 1 replica (there's a apiservice linked to it)
- tapInjector only 1 replica (there's a webhook linked to it)
- set proper `namespaceSelector` for the tapInjector webhook (ignore kube-system, cert-manager and giantswarm NS)
- disable prometheus by default (?)

**Comment by mcharriere** [comment]
> disable prometheus by default 

we won't do that for now, as using an alternative is highly dependent on the monitoring stack.

**Comment by mcharriere** [comment]
v1.1.0 released 🚀

**Comment by ubergesundheit** [comment]
I think there is an error in the values.yaml

The `namespaceSelector` is missing a `matchExpressions`:

```
tapInjector:
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - cert-manager
      - giantswarm
```
