### ISSUE TITLE
introduce roleBindingTemplate

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#2706]
The purpose of the `RoleBindingTemplate` is to dynamically create `RoleBindings` in all or certain organizations.
An operator reconciles `RoleBindingTemplate` CRs and and creates the bindings based on its spec inside the namespaces within the defined scope.
The CRD is cluster-scoped.

Sketch
```
apiVersion: something.giantswarm.io/v1
kind: roleBindingTemplate
metadata:
  name: example
spec:
  description: "We are allowing the thing to do the thing"
  template:
    spec:
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: example-role
      subjects:
      - kind: ServiceAccount
        name: automation 
      - kind: ServiceAccount
        name: automation 
        namespace: default  # when no namespace is given for namespaced resource, we use the namespace it's templated to
  scopes:
    organizationSelector:
      matchLabels: # if this matcher is empty, we want to apply to every organization
        key: value
```

We want to start with this simple spec that can be extended later if needed.

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/roadmap/issues/2707
- [ ] https://github.com/giantswarm/roadmap/issues/2709
- [ ] https://github.com/giantswarm/roadmap/issues/2723
- [ ] https://github.com/giantswarm/roadmap/issues/2730
```
