### ISSUE TITLE
Default deny-all policies in WCs

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/roadmap#2815]
In scope of https://github.com/giantswarm/roadmap/issues/1949 we introduced `default-deny-all`  NetworkPolicy resources in `kube-system` and `giantswarm` like below:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: kube-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: giantswarm
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
```

Currently we are creating them only in MCs with `mc-bootstrap` in `scripts/setup-cmc.sh` script. This basically means they are basically managed from CMC repository.

That was a shortcut and is not going to work for WCs. How we should do this so it works for both?

Please note WCs also have the `giantswarm` namespace. `chart-operator` is running there.
