### ISSUE TITLE
Test Honeybadger components on GS EKS based CAPA solution

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2818]
Following Phoenix development on EKS cluster creation based on CAPA, we have created a solution to create the EKS clusters within our current stack on CAPA MCs. The full documentation can be found here: https://intranet.giantswarm.io/docs/dev-and-releng/capi-eks-internal-doc/.

Now is up to the Product teams to test out EKS on CAPA in order to gather further notes on development and missing features from other teams. Please take this into account while also testing out the Honeybadger 'import' of EKS.

cc @puja108 for planning

**Comment by ljakimczuk** [comment]
Apps the installation of which has been tested:
- [ ] external-secrets
- [ ] flux
- [ ] gitops-server
- [ ] harbor-config-operator
- [ ] harbor-operator
- [ ] hello-world
- [ ] backstage
- [ ] crossplane

**Comment by ljakimczuk** [comment]
## External Secret Test Setup

```yaml
---
apiVersion: v1
data:
  values: |
    crds:
      createClusterExternalSecret: true
      createClusterSecretStore: true
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ljakim00-external-secrets-userconfig-ljakim00
  namespace: org-giantswarm
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    giantswarm.io/cluster: ljakim00
  name: ljakim00-external-secrets
  namespace: org-giantswarm
spec:
  catalog: giantswarm
  kubeConfig:
    inCluster: false
  name: external-secrets
  namespace: default
  userConfig:
    configMap:
      name: ljakim00-external-secrets-userconfig-ljakim00
      namespace: org-giantswarm
  version: 0.6.6
```

**Comment by ljakimczuk** [comment]
## Flux Test Setup

```yaml
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    giantswarm.io/cluster: ljakim00
  name: ljakim00-flux
  namespace: org-giantswarm
spec:
  catalog: giantswarm
  kubeConfig:
    inCluster: false
  name: flux-app
  namespace: default
  version: 1.0.0
```
