### ISSUE TITLE
Installation/Upgrade of kong causes network hickup

### ISSUE THREAD

**Issue by ubergesundheit** [giantswarm/roadmap#2878]
kong-app chart uses a special Job for installing and upgrading CRDs. this Job contains a NetworkPolicy tailored for the Job to reach the kubernetes api.

Related Slack thread: https://gigantic.slack.com/archives/C0128MNQABZ/p1697004259434189

**Comment by FelipeSolanaAdidas** [comment]
Every time that helm installation fail, for example the docker image does not exist, the process is continually creating a networpolicy called
kong-app-crd-install, on kong internal this policy is created and kept blocking totally the comunications with the cluster, in kong external
the policy is created and kept during few seconds until removed and then in a period of time is created again, meanwhile this policy exist is blocking the request and provoke latency on the clients.


Feel free to try reproduce the error on apie1. Warn us if you do some test

You can test with this curl, get a 401 will be the expected behavior if you prefer test with 200 please ask me about the api-key 

External:
`curl https://kong-test-apie1.api.3stripes.io/echo/test/order`
Internal:
`curl https://kong-test-apie1.int.api.3stripes.io/echo/test/order`

You will get timeout or high latency when the policy is kept

**Comment by FelipeSolanaAdidas** [comment]
@ubergesundheit  Could you add the label `adidas/kong` to include in the dashboard

**Comment by ubergesundheit** [comment]
Thanks for letting us use `apie1` for investigations. I tried to reproduce the issue by:

Running a continious curl in one terminal (Expecting 401 responses because of missing api key)

```
while true; do ./curl-amd64 https://kong-test-apie1.api.3stripes.io/echo/test/order -w "%{num_connects}, %{http_code}, %{time_total}, %{time_connect}, %{time_namelookup}, %{time_pretransfer}, %{time_redirect}, %{time_starttransfer}, %header{date}, %{errormsg}\n" -o /dev/null -s --max-time 10  ; done
```

Then triggering a helm upgrade by removing the `chart-operator.giantswarm.io/values-md5-checksum` annotation from the `kong-app` Chart CR on the cluster.

Sadly I was not able to reproduce the issue. Calls of curl showed a consistent response time

Have you ever observed this behaviour on `apie1`? How did you measure the timeouts or high latencies?

**Comment by FelipeSolanaAdidas** [comment]
The error happened when the helm installation is failed. I suggest you put a non existing image to provoke the same problem that in China yesterday. In some point the issue happen, but is not immediate.

**Comment by ubergesundheit** [comment]
Ok I'll try this now

**Comment by FelipeSolanaAdidas** [comment]
The case is reproduce when the correct releseNames is used 

If you apply manullly as the same way that is applied by the helm chart then the problem appears.

For me there are two options.
1. Not apply the policy, it is necessary
2. Apply egress rules to avoid the problem

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
  labels:
    app.kubernetes.io/component: kong-app-crd-install
    app.kubernetes.io/instance: kong-app-internal
    app.kubernetes.io/name: kong-app
    app.kubernetes.io/version: 2.8.1
    application.giantswarm.io/container-images-hash: 7e3c7ec73343695b45e580406cdf453f4cda0cbfec1a0bd6121c2940991d4b3
    application.giantswarm.io/team: team-cabbage
    role: crd-install-hook
  name: kong-app-crd-install
  namespace: kong-internal
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    - port: 6443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 10.0.0.0/8
    - ipBlock:
        cidr: 172.16.0.0/12
    - ipBlock:
        cidr: 192.168.0.0/16
    - ipBlock:
        cidr: 100.64.0.0/10
  podSelector:
    matchLabels:
      app.kubernetes.io/component: app
      app.kubernetes.io/instance: kong-app-internal
      app.kubernetes.io/name: kong-app
  policyTypes:
  - Egress
  - Ingress
status: {}
```

**Comment by ubergesundheit** [comment]
Applying the following NetworkPolicy to kong namespaces should override the crd networkpolicy

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: kong-manual
  namespace: "kong-internal"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: "kong-app"
      app.kubernetes.io/component: app
      app.kubernetes.io/instance: "kong-app-internal"
  # allow all egress
  egress:
  - {}
  # allow all ingress
  ingress:
  - {}
  policyTypes:
  - Egress
  - Ingress
```
