### ISSUE TITLE
Node tainting during migration to CAPA

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3008]
One of the key features to pay attention to during migration is to support the `k8s-initiator-app` feature of node-tainting.

Node tainting is directly available in CAPA and can be configured accordingly. Hence every customer has to migrate away from using this feature in Vintage clusters via the mentioned application. 

1. We recognized that customers do use `giantswarm.io/machine-deployment` label to schedule the workloads on given Node Pools. As CAPA uses the concept of Machine Pool, the label is changed to `giantswarm.io/machine-pool`. In order to not break customer scheduling preferences, we will adjust the migration script to also keep the 'machine-deployment' label for initial consistency. This way customers will be able to adjust their deployments accordingly after the migration.

- [x] Adjust migration CLI script to migrate `giantswarm.io/machine-deployment` along with new `giantswarm.io/machine-pool` label per nodepool.

2. As `k8s-initiator-app` enables customers to work with custom bash scripts, we have to standardize the node-tainting on vintage clusters such that the settings can be easily migrated and applied on newly created CAPA clusters. For this purpose we would ask AEs to work together with customers to create a configmap per cluster in cluster namespace called `migration-configuration-{cluster_name}.yaml` with a following [structure](https://github.com/giantswarm/cluster-aws/blob/master/helm/cluster-aws/values.schema.json#L12) that follows the CAPA semantics for cluster configuration. This file will be also extended with more features that customers use via the `k8s-initiator-app`.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {cluster_name}-migration-configuration
  namespace: {cluster_namespace}
data: 
  values: |
    global:
      nodePools:
        {node_pool_name}:
          customNodeLabels:
          - node-custom-label=elastic
          customNodeTaints:
          - effect: NoSchedule
            key: elasticsearch
            value: dedicated
            operator: Equal
```
