### ISSUE TITLE
figure out how we can make WC deployed apps to use the new registries

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#3044]

**Comment by uvegla** [comment]
Catalogs are the base layer upon all other configurations are merged ([ref](https://docs.giantswarm.io/getting-started/app-platform/app-configuration/#levels)) when they are reconciled by `app-operator`.

We have the catalog bases configured in MCB: https://github.com/giantswarm/management-cluster-bases/tree/main/bases/catalogs and we have some overrides / MC specific values in CMC repos, example: https://github.com/giantswarm/management-cluster-bases/tree/main/bases/catalogs

Intentionally linked the above MC as it represents how varied the image registry can be configured for each app. There are some conventions and generic places that we can easily go for to have a good impact tho:

```yaml
            image:
              registry: <DESIRED_REGISTRY_GOES_HERE>

            global:
              imageRegistry: <DESIRED_REGISTRY_GOES_HERE>
              image:
                registry: <DESIRED_REGISTRY_GOES_HERE>

            registry:
              domain: <DESIRED_REGISTRY_GOES_HERE>
```
