### ISSUE TITLE
Use new GS registry for core images in the `cluster-aws` chart

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#3109]
## Task

Use new GS registry for core images in the `cluster-aws` chart.

## Backround

The `cluster-aws` chart has a reference to `docker.io` in the `KubeadmControlPlane` definition.

```
{{- define "control-plane" }}
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "labels.common" $ | nindent 4 }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
  name: {{ include "resource.default.name" $ }}
  namespace: {{ $.Release.Namespace }}
spec:
  machineTemplate:
    ...
  kubeadmConfigSpec:
    ...
    clusterConfiguration:
      # Avoid accessibility issues (e.g. on private clusters) and potential future rate limits for the default `registry.k8s.io`
      imageRepository: docker.io/giantswarm
```

## Links
- [Epic](https://github.com/giantswarm/roadmap/issues/2882).
- [State after initial investigation](https://github.com/giantswarm/roadmap/issues/2882#issuecomment-1884849813);
