### ISSUE TITLE
Use new GS registry for core images in the `cluster` chart

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#3110]
## Task

Use new GS registry for core images in the `cluster` chart.

## Backround

The `cluster` chart has a reference to `docker.io` in the `KubeadmControlPlane` definition.

```
{{- if $.Values.providerIntegration.resourcesApi.controlPlaneResourceEnabled }}
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  ...
spec:
  machineTemplate:
    ...
  kubeadmConfigSpec:
    ...
    clusterConfiguration:
      # Avoid accessibility issues (e.g. on private clusters) and potential future rate limits for
      # the default `registry.k8s.io`.
      imageRepository: docker.io/giantswarm
```

## Links
- [Epic](https://github.com/giantswarm/roadmap/issues/2882);
- [State after initial investigation](https://github.com/giantswarm/roadmap/issues/2882#issuecomment-1884849813).
