### ISSUE TITLE
Ingest data within Mimir

### ISSUE THREAD

**Issue by marieroque** [giantswarm/roadmap#3152]
First work: https://github.com/giantswarm/roadmap/issues/2266

**Comment by marieroque** [comment]
Remote write added on `golem`:
```
apiVersion: monitoring.giantswarm.io/v1alpha1
kind: RemoteWrite
  labels:
    application.giantswarm.io/team: atlas
  name: mimir
  namespace: mimir
spec:
  clusterSelector: {}
  remoteWrite:
    name: mimir
    queueConfig:
      capacity: 10000
      maxSamplesPerSend: 1000
      minShards: 10
    tlsConfig:
      insecureSkipVerify: false
    url: http://mimir-gateway.mimir.svc/api/v1/push
```

**Comment by marieroque** [comment]
mimir `datasource` added on grafana:


![Image](https://github.com/giantswarm/roadmap/assets/9134338/54d23b37-0f7e-4333-97cf-77b559dfff4e)

**Comment by marieroque** [comment]
We can see metrics from `mimir`:


![Image](https://github.com/giantswarm/roadmap/assets/9134338/6fb687ac-9c04-4eca-81ee-559c6b02c17f)

**Comment by marieroque** [comment]
`ingester` and `store-gateway` trace those warnings:
```
ts=2024-01-18T14:48:43.47010923Z caller=seed.go:90 level=warn msg="failed to create cluster seed file" err="mkdir /blocks: read-only file system"            
```

To remove them, we set in `ingester` and `store-gateway` values:
```
securityContext:
    readOnlyRootFilesystem: false
```

Now, `store-gateway` has no more warning.

But `ingesters` have those errors:
```
ts=2024-01-18T15:05:25.256967967Z caller=seed.go:90 level=warn msg="failed to create cluster seed file" err="mkdir /blocks: permission denied"
ts=2024-01-18T15:05:28.644840673Z caller=shipper.go:158 level=info user=anonymous msg="uploading new block to long-term storage" block=01HMEET5GHBWAPWM5S8TTJ7GGM
ts=2024-01-18T15:05:28.645010779Z caller=shipper.go:162 level=error user=anonymous msg="uploading new block to long-term storage failed" block=01HMEET5GHBWAPWM5S8TTJ7GGM err="upload chunks: upload file /data/tsdb/anonymous/01HMEET5GHBWAPWM5S8TTJ7GGM/chunks/000001 as 01HMEET5GHBWAPWM5S8TTJ7GGM/chunks/000001: mkdir /blocks: permission denied"
```

**Comment by QuentinBisson** [comment]
@marieroque was this done by hand?? How was this deployed?

**Comment by QuantumEnigmaa** [comment]
The `mimir` sa used by all mimir pods, `ingester` included has the IRSA annotation : `eks.amazonaws.com/role-arn: arn:aws:iam::<whatever>:role/giantswarm-golem-mimir`. 
And on AWS side, the corresponding role has the adequate policy : 
```
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Effect": "Allow",
			"Action": [
				"s3:ListBucket",
				"s3:PutObject",
				"s3:GetObject",
				"s3:DeleteObject"
			],
			"Resource": [
				"arn:aws:s3:::giantswarm-golem-mimir",
				"arn:aws:s3:::giantswarm-golem-mimir/*"
			]
		},
		{
			"Effect": "Allow",
			"Action": [
				"s3:GetAccessPoint",
				"s3:GetAccountPublicAccessBlock",
				"s3:ListAccessPoints"
			],
			"Resource": "*"
		}
	]
}
```
Still the ingrester pods get the `permission denied` error when trying to write on the bucket, so I'm wondering if IRSA is actually working on `golem`

**Comment by QuentinBisson** [comment]
Did you restart the pod ? If yes I would Ask phoenix :)

**Comment by QuantumEnigmaa** [comment]
I did :/

**Comment by QuantumEnigmaa** [comment]
Loki is working well on `golem` so IRSA is working. I tried downloading the aws cli on an ingester pod to try to reach the S3 bucket from inside the container but I can't `wget` the zip file because of non-sufficient permissions :/

I created a discussion [here](https://github.com/grafana/mimir/discussions/7200) to ask help from mimir people.
If it doesn't get a reply, I'll create an issue tomorrow

**Comment by QuantumEnigmaa** [comment]
Thx to the upstream fix, the error from the `ingester` pod has changed : 
```
level=error msg="error running application" err="no s3 endpoint in config file
```

When looking at the `mimir-config` cm in the `mimir` ns, I saw that the `common` part of the structuredConfig where the bucket endpoint and region is defined as well as the `s3` field for block storage was no present on this cm : 
```
    blocks_storage:
      backend: s3
      bucket_store:
        sync_dir: /data/tsdb-sync
      tsdb:
        dir: /data/tsdb
        head_compaction_interval: 15m
        wal_replay_concurrency: 3
```

However the `mimir-chart-values` cm in the `giantswarm` ns is as follows : 
```
structuredConfig:
        blocks_storage:
          backend: s3
          bucket_store:
            max_chunk_pool_bytes: 12884901888
            sync_dir: /data/tsdb-sync
          s3:
            bucket_name: giantswarm-golem-mimir
        common:
          storage:
            s3:
              endpoint: s3.eu-west-2.amazonaws.com
              region: eu-west-2
            type: s3
```

So there must be a propagation issue of some kind. 

I tried modifying the `mimir-config` directly as such : 
```
          s3:
            bucket_name: giantswarm-golem-mimir
            endpoint: s3.eu-west-2.amazonaws.com
            region: eu-west-2
```

But then the ingester logs were : 
```
level=error msg="Unable to successfully connect to configured object storage" err="blocks storage: unable to successfully send a request to object storage: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
```

Maybe this is because I didn't add the `common` field as well.

**Comment by QuantumEnigmaa** [comment]
I was able to make the ingester pods push their metrics to the S3 bucket (cf below screenshot) by editing the `mimir-config` configmap in the `mimir` namespace so that it looks like this : 
```
    blocks_storage:
      bucket_store:
        sync_dir: /data/tsdb-sync
      tsdb:
        dir: /data/tsdb
        head_compaction_interval: 15m
        wal_replay_concurrency: 3
      s3:
        bucket_name: giantswarm-golem-mimir
    common:
      storage:
        backend: s3
        s3:
          endpoint: s3.eu-west-2.amazonaws.com
          region: eu-west-2
```

![image](https://github.com/giantswarm/roadmap/assets/64951262/79f5346a-fb57-44a4-b338-469cce9d836b)

However, even after updating the configmap in the `config` repo to match this, the `mimir-config` generated do not have the config passed so i have to find what's blocking this.
