### ISSUE TITLE
Teleport for EKS cluster access

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#3156]
We have been [requested by teams](https://gigantic.slack.com/archives/C52L7C6SC/p1705503987203459?thread_ts=1701263781.939559&cid=C52L7C6SC) about EKS cluster access via Teleport.

`snail` MC is being used to test pure EKS as WC, by honeybadger. Maybe talk with them first.

**Comment by ssyno** [comment]
The `teleport-kube-agent` got successfully deployed on `teletest` EKS WC on this [PR](https://github.com/giantswarm/default-apps-eks/pull/74).
```
tsh kube login snail-teletest
k get nodes -o wide
NAME                                             STATUS   ROLES    AGE     VERSION                INTERNAL-IP     EXTERNAL-IP     OS-IMAGE         KERNEL-VERSION                  CONTAINER-RUNTIME
ip-10-0-216-54.eu-central-1.compute.internal     Ready    worker   3h51m   v1.24.17-eks-5e0fdde   10.0.216.54     <none>          Amazon Linux 2   5.10.205-195.804.amzn2.x86_64   containerd://1.7.2
ip-10-0-29-125.eu-central-1.compute.internal     Ready    worker   3h51m   v1.24.17-eks-5e0fdde   10.0.29.125     18.198.26.205   Amazon Linux 2   5.10.205-195.804.amzn2.x86_64   containerd://1.7.2
ip-100-64-19-154.eu-central-1.compute.internal   Ready    worker   3h51m   v1.24.17-eks-5e0fdde   100.64.19.154   <none>          Amazon Linux 2   5.10.205-195.804.amzn2.x86_64   containerd://1.7.2
```
The main issue inside the EKS WC was that `coreDNS` was missing and pod were unable to resolve its statically set ip at `172.31.0.10:53`. After adding it on the default apps `coreDNS` was trying to start on `10.96.0.0/12` network, so a further changes were needed in `teletest-cluster-values` configmap.
```
apiVersion: v1
data:
  values: |
    baseDomain: teletest.gaws.gigantic.io
    bootstrapMode:
      apiServerPodPort: 6443
      enabled: false
    chartOperator:
      cni:
        install: false
    cluster:
      calico:
        CIDR: 100.64.0.0/16
      kubernetes:
        API:
          clusterIPRange: 10.96.0.0/12 --> 172.31.0.0/12
        DNS:
          IP: 10.96.0.10
      private: false
    clusterCA: ""
    clusterCIDR: ""
    clusterDNSIP: 10.96.0.10 --> 172.31.0.10
    clusterID: teletest
    gcpProject: ""
    provider: capa
kind: ConfigMap
metadata:
  annotations:
    giantswarm.io/notes: DO NOT EDIT. Values managed by cluster-apps-operator.
  labels:
    app-operator.giantswarm.io/watching: "true"
    giantswarm.io/cluster: teletest
    giantswarm.io/managed-by: cluster-apps-operator
  name: teletest-cluster-values
  namespace: org-bigmac

```
