### ISSUE TITLE
Enable logging on one CAPV test installation using https://github.com/giantswarm/giantswarm/issues/29177#issuecomment-1877499101

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#3165]

**Comment by QuentinBisson** [comment]
Create bucket on `glippy` for bamboo:

```yaml
apiVersion: objectstorage.giantswarm.io/v1alpha1
kind: Bucket
metadata:
  name: giantswarm-bamboo-loki
  namespace: loki
spec:
  accessRole:
    roleName: giantswarm-bamboo-loki
    serviceAccountName: loki
    serviceAccountNamespace: loki
  expirationPolicy:
    days: 100
  name: giantswarm-bamboo-loki
  tags:
  - key: app
    value: loki
  - key: installation
    value: bamboo
  - key: name
    value: giantswarm-bamboo-loki
```
