### ISSUE TITLE
Propose a schema of universal values.yaml options to be used and enforced across all apps

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#3185]
We need to come up with a defined schema for configuration values that are shared across multiple/all apps. A good example of the problem we have right now is the configuration of the image registry URL, which is now configured in at least 6 different ways ([ticket](https://github.com/giantswarm/roadmap/issues/3044)).

**Comment by piontec** [comment]
Proposed schema:

```yaml
global:
  podSecurityStandards:
    enforced: false
```

**Comment by marians** [comment]
Regarding JSON schema dereferencing: I think we build this into [schemalint](https://github.com/giantswarm/schemalint). Despite the name, schemalint already has a helper command `normalize`. I am pretty sure the code for this is already in place in the tool. I could well imagine another command `deref` only for that purpose.

Apart from that, I have looked for dedicated tools, but found nothing.

**Comment by uvegla** [comment]
- How about namespacing all our values under `giantswarm`? Not all charts are managed via sub charts and this way we can avoid all conflicts / confusion of stuff coming from upstream and how we define them.
- I get `images. registry` cos ideally it should be same for all. How about supporting it per image instead? It would still make it easy for an automation later to update all of them lets say, but gives more flexibility. Also an option if a per image one is not defnied, then use the one under images. For that tho I prefere 1 way of doing things instead of implementing a fallback in all charts.

**Comment by piontec** [comment]
Problems and issues:
- YAML anchors don't work because it's helm
- `[key].[container/pod_name]` keys are a bad idea as they are not overridable - let's use defaults
- 2 sections for optional: optional well-known and optional for-consistency

**Comment by piontec** [comment]
# v20240429-1

### Schema

```yaml
### All keys here placed under "global", so they are available to sub-charts as well
global:
  # ###
  # Mandatory well-known top level keys - have to be present and have this structure
  # We use them everywhere to drive region/MC/WC specific settings for multiple charts
  # from a single source of configuration.
  # ###
  images:
    registry: [gsoci.azurecr.io]
    "<imagePullSecrets>":
      - [SecretName]
    "[main]":
      image: giantswarm/[image]
      tag: [TAG]
      "<pullPolicy>": [IfNotPresent]
      "<registry>":
        [gsociprivate.azurecr.io] # do that only if you want to override the default;
        # this won't be managed by external global config settings
    "[alpine]":
      image: giantswarm/alpine
      tag: "3.18"
      "<pullPolicy>": [IfNotPresent]

  # ###
  # Optional well-known top level keys - they don't have to be present, but if they are,
  # they have to have this structure.
  # We use them everywhere to drive region/MC/WC specific settings for multiple charts
  # from a single source of configuration.
  # ###

  podSecurityStandards:
    enforced: false

  ###
  # Optional keys - they are not used to enforce common settings, but to keep most popular settings
  # in sync, so we have consistency when working on charts. These values won't be set for multiple charts
  # at the same time, like from CCRs, but we still want to have the settings consitent, if used.
  # ###

  verticalPodAutoscaler:
    enabled: true

  podDisruptionBudget:
    enabled: false

  crds:
   install: true

  # defined for the main pod (default), then for each pod with different requirements by pod's name
  resources:
    default:
      "<requests>":
        cpu: 500m
        memory: 512Mi
      "<limits>":
        cpu: 1000m
        memory: 1024Mi
    "[alpine]":
      "<requests>":
        cpu: 500m
        memory: 512Mi
      "<limits>":
        cpu: 1000m
        memory: 1024Mi

  # defined for the main pod (default), then for each pod with different requirements by pod's name
  tolerations:
    default: []
    "[alpine]": []
  nodeSelector:
    default: {}
    "[alpine]": {}
  affinity:
    default: {}
    "[alpine]": {}

  podSecurityContext:
    default:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    "[alpine]":
      runAsNonRoot: false
  containerSecurityContext:
    default:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
    "[alpine]":
      runAsNonRoot: false
```

### Examples

#### Simple pod with 1 container and security policies

```yaml
images:
  registry: gsoci.azurecr.io
  zot:
    image: giantswarm/zot-linux-amd64
    tag: "2.3.4"
  alpine:
    image: giantswarm/alpine
    tag: "3.18"

securityContextBase: &securityContextBase
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  seccompProfile:
    type: RuntimeDefault
podSecurityContext:
  <<: *securityContextBase
  fsGroup: 1000
  fsGroupChangePolicy: "OnRootMismatch"
containerSecurityContext:
  <<: *securityContextBase
  allowPrivilegeEscalation: false
```

#### Pod with 2 containers and extra options

```yaml
images:
  registry: gsoci.azurecr.io
  imagePullSecrets:
    - dockerhub-pull-secret
  zot:
    image: giantswarm/zot-linux-amd64
    tag: "2.3.4"
  alpine:
    image: giantswarm/alpine
    tag: "3.18"

resources:
  zot:
    requests:
      cpu: 2000m
      memory: 1024Mi
    limits:
      cpu: 2000m
      memory: 1024Mi
  alpine:
    requests:
      cpu: 500m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 128Mi

securityContextBase: &securityContextBase
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  seccompProfile:
    type: RuntimeDefault
podSecurityContext:
  <<: *securityContextBase
  fsGroup: 1000
  fsGroupChangePolicy: "OnRootMismatch"
containerSecurityContexts:
  zot:
    <<: *securityContextBase
    runAsGroup: 2000
  alpine:
    <<: *securityContextBase
    allowPrivilegeEscalation: false
```

#### Sub-charts with many pods, containers and extra options

```yaml
images: &images
  registry: gsoci.azurecr.io
  imagePullSecrets:
    - dockerhub-pull-secret
  zot:
    image: giantswarm/zot-linux-amd64
    tag: "2.3.4"
  alpine:
    image: giantswarm/alpine
    tag: "3.18"
  postgres:
    image: giantswarm/postgres
    tag: "10.11.2"
  minio:
    image: giantswarm/minio
    tag: "3.4.5"

verticalPodAutoscaler: &vpa
  enabled: true
podSecurityStandards: &pss
  enforced: true
podDisruptionBudget: &pdb
  enabled: true
crds: &crds
  install: true

# same tolerations for all the pods
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

# pass all the options to sub-charts
global:
  images: *images
  verticalPodAutoscaler: *vpa
  podSecurityStandards: *pss
  pdb: *pdb
  crds: *crds
```

**Comment by uvegla** [comment]
Just a minor thing, but the read / usability of the values file takes precedence I think. On nodes where there there are component names like [main], [alpine], etc. it might be simpler to validate / programatically update them if they are separated under a key, may it be however named. Otherwise it is not straightforward to know which nodes are component nodes are supposed to have e.g. `image` and `tag` if other object type fields are possible. Let's say:

```yaml
global:
  images:
    registry: gsoci.azurecr.io
    kustomize-controller:
      image: giantswarm/kustomize-controller
      tag: v1.0.1
   source-controller:
     image: giantswarm/fluxcd-source-controller
     tag: v1.0.1
  more:
    properties:
      a: 1
      b: 2
```

From a validation tools standpoint: is `more` a container and should have image and tag?
