### ISSUE TITLE
Send remote write data from agents to Mimir directly (short-circuiting MC prometheus)

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#3217]
Once we have mimir ready, let's send data from the agents to mimir directly without going through the Prometheus on the MC

**Comment by QuentinBisson** [comment]
Sure go ahead :) thé PRs in observability operator to take over the agent config and thé pr in pmo to not manage prometheus agent config were towards this issue

**Comment by QuentinBisson** [comment]
I would think the first step is to enable the ingress and add the multi-tenant proxy to Mimir ?

**Comment by QuantumEnigmaa** [comment]
> I would think the first step is to enable the ingress and add the multi-tenant proxy to Mimir ?

That's also what I was thinking :)

**Comment by QuantumEnigmaa** [comment]
There is something with how the ingress is configured upstream, leading to our app to fail while trying to deploy the ingress : 
```
template: mimir/charts/mimir/templates/ingress.yaml:31:19: executing "mimir/charts/mimir/templates/ingress.yaml" at <.>: wrong type for value; expected string; got map[string]interface {}
```

Looks like this part of the upstream chart was not touched for a long time : 

* In the values, the ingress is defined in the `nginx.ingress` section
* In the ingress resource template, every ingress fields is retrieved from `.Values.ingress` so obviously there's something wrong. 

And according to the error message from our mimir, there's even more to it than this.

**Comment by Rotfuks** [comment]
We need to fix this upstream. 
We decided to stick to just push the change in the upstream helm charts, because the change upstream is potentially faster then creating and managing our own fork. So let's try it and monitor how long this takes :)

**Comment by QuantumEnigmaa** [comment]
Upstream PR : https://github.com/grafana/mimir/pull/7933

**Comment by QuantumEnigmaa** [comment]
After further investigation in the upstream chart, I found out there were multiple ingress resources templates defined in the chart, among which one for the gateway. I tried it and it works perfectly so I closed the upstream PR.

Now the ingress for mimir-gateway is deployed on `golem` alongside basicAuth needed to use it with the following config : 
```yaml
gateway:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-giantswarm
      hosts:
      - host: mimir.golem.gaws.gigantic.io
        paths:
        - path: /api/V1/push
          pathType: ImplementationSpecific
      tls:
      - secretName: mimir-nginx-tls
        hosts:
          - mimir.golem.gaws.gigantic.io
    nginx:
      basicAuth:
        enabled: true
        username: <username>
        password: <password>
``` 

This created the `mimir-gateway` ingress in the `mimir` namespace as well as the `mimir-gateway-nginx` secret, which has the following data : 
```yaml
data:
  .htpasswd: <base64_encrypted>
```

As mentioned in the upstream chart, the `htpasswd` : 
> Uses the specified username and password to compute a htpasswd using Sprig's `htpasswd` function

I'm now focused on updating PMO code to enable the creation of a remote-write-secret compatible with the use of the `mimir-gateway` ingress alongside the generated password.
