### ISSUE TITLE
Report about the nginx ingress controller in the SLA reporting dashboard

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#3229]
Atlas recently added a new dashboard to report about our SLAs in this PR https://github.com/giantswarm/dashboards/pull/433/files.

We have SLAs on nginx and those should be added to this dashboard.

What we would like is for you to create a slo using sloth the expose the `availability` of the `public nginx ingress controller` that is optionally deployed in the clusters.

Here is an example of an slo alert https://github.com/giantswarm/sloth-rules/blob/5a0ee4a6c65dfdd849d197cd3b873d8fa342dec4/areas/kaas/teams/phoenix/apiserver/slos/availability.yaml

Feel free to ask @giantswarm/team-atlas for help to create the SLO rule and alert and to integrate the data in the dashboard

**Comment by weatherhog** [comment]
@QuentinBisson I understood that this is not urgent and that's why it is living in our backlog at the moment without a clear ETA. Let me know if there is some urgency from atlas to get this done, so that we can rearrange in cabbage.

**Comment by QuentinBisson** [comment]
Coming from the umbrella issue I thought it was quite important for customers https://github.com/giantswarm/roadmap/issues/3228#issuecomment-1960945105 :D

**Comment by QuentinBisson** [comment]
@LolloneS any thoughts on the matter?

**Comment by mcharriere** [comment]
> What we would like is for you to create a slo using sloth the expose the availability of the public nginx ingress controller that is optionally deployed in the clusters.

I think we need to get this a bit more clear before proceeding: What does `availability` mean for our customers?

Let's say we used the `nginx_ingress_controller_requests` metric, that'd actually say nothing about nginx but rather about the workload. Any other metric showing the "controller" health (like admission) might look ok, but it may not have enough samples to provide any useful information and it doesn't actually show that nginx works.

There is then, the "latency" aspect of the availability. What value is considered fast enough to pass the availability check?

**Comment by QuentinBisson** [comment]
I think this should be about our availability not the one from the customer though

**Comment by mcharriere** [comment]
> As a customer, I want to be able to see the availability of the important kubernetes components and check if they are respecting the agreed SLAs.

I'm taking this from the main ticket. I don't think there is a correct definition of what we need to do here.
- What is the agreed SLA? For which SLI?
- `availability` is too broad

maybe @LolloneS can help us here.

Also, the dashboard is `SLO Reporting` on Grafana, right? Are you going to make it public at some point?

**Comment by QuentinBisson** [comment]
It is currently private but yes it will be public once all cabbage SLOs are there.
I agree that this is too broad and you need to define what the availability is . The agreed SLA  in the contracts is  of 99.5 availability but then we should be the one to decide what we mean with availability

**Comment by LolloneS** [comment]
@mcharriere I think that, as always, we should start with something simple and then iterate on it.

- the agreed SLA is 99.95% IIRC
- `availability` in this case refers to the Nginx deployment actually being up&running and serving requests. a ping once a minute to a dummy Ingress is all we need

**Comment by mcharriere** [comment]
> availability in this case refers to the Nginx deployment actually being up&running and serving requests. a ping once a minute to a dummy Ingress is all we need

I see. I added this to refinement to discuss our options. 
At first glance, I don't think we have the infrastructure to generate synthetic traffic from outside the cluster, but maybe from the inside is enough.

**Comment by mcharriere** [comment]
> I think we should bé able to use the blackbox exporter or a prometheus operator probe from thé MC though

As we recently learned in SIG arch, that's not always guaranteed. For example, let's take the case of a public installation, where the MC probes both the public and the private ingress controller running on the WC.

The public ingress will work fine, but the private ingress will fail. And vice versa.

![image](https://github.com/giantswarm/roadmap/assets/11235884/451ad6aa-5671-4bc8-9f81-6ac4ef27ccb5)

Also, a dummy ingress means that the unavailability of that backend counts for the SLA. Also, we could probably use the default-backend so there is no need for an App on its own.

---

To try to avoid all this MC/WC connectivity issues, I'd say we start with in-cluster traffic alone.
We could change net-exporter to query some predefined ingresses pointing to the default-backend. 

![image](https://github.com/giantswarm/roadmap/assets/11235884/9f10ded1-7c10-412b-b08d-012375fb1c7b)

**Comment by mcharriere** [comment]
We decided for the first iteration to go with a solution confined to net-exporter, where we expose a /healthz endpoint and install N ingresses; where should be check every some customizable interval.

![image](https://github.com/giantswarm/roadmap/assets/11235884/78a6bedb-dedd-4839-8df7-cacfd48d387f)

We'll report the SLO based on those metrics.

**Comment by kopiczko** [comment]
Things we agreed on in Slack:

- `net-exporter` deploys ingress with the helm chart (configurable) - UX-wise it isn't great because we'll need to have that configured in separate app, after `(internal) ingress`, or `kong` is installed
- `net-exporter` exposes the metric and pings itself in the exporter

**Comment by kopiczko** [comment]
- `exporterkit` PR enabling exposing extra `/blackbox` endpoint in `net-exporter` https://github.com/giantswarm/exporterkit/pull/95 (details in the PR description)

**Comment by kopiczko** [comment]
Feels like everything is done on our side. We have:

- https://github.com/giantswarm/ingress-sla-app with [requirements PR](https://github.com/giantswarm/ingress-sla-app/pull/11) to be merged
- (our dependency) net-exporter is released and all `default-apps-*` received updates (but they are not released yet), we'll need to wait for the releases and then update the requirements
- SLO rules are merged https://github.com/giantswarm/sloth-rules/pull/179 - I think it's for Team Atlas to release and update dashboards

The small thing that's left is ops recipe, but PRs are open.

I'd like to create a small follow up issue with those tasks:
- revisit https://github.com/giantswarm/sloth-rules/pull/179 PR and set `cancel_if_outside_working_hours: '{{ include "workingHoursOnly" . }}'`
- update `ingress-sla-app` [requirements PR](https://github.com/giantswarm/ingress-sla-app/pull/11) with the actual versions when `default-apps-<provider>` is released

And close this.  @QuentinBisson WDYT?

**Comment by QuentinBisson** [comment]
Did you add the app to the cluster default apps ? I think the PR is missing here unless I'm mistaken but then you should be done and I can take over and add the recording rules to the sla dashboard

**Comment by kopiczko** [comment]
@QuentinBisson that should get you a EKS cluster with everything setup:

```yaml
---
apiVersion: v1
data:
  values: |
    global:
      metadata:
        name: quentin1ove
        organization: pawel
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    giantswarm.io/cluster: quentin1ove
  name: quentin1ove-userconfig
  namespace: org-pawel
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
  name: quentin1ove
  namespace: org-pawel
spec:
  catalog: cluster
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: cluster-eks
  namespace: org-pawel
  userConfig:
    configMap:
      name: quentin1ove-userconfig
      namespace: org-pawel
  version: 0.16.0
---
apiVersion: v1
data:
  values: |
    clusterName: quentin1ove
    organization: pawel
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    giantswarm.io/cluster: quentin1ove
  name: quentin1ove-default-apps-userconfig
  namespace: org-pawel
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    giantswarm.io/cluster: quentin1ove
    giantswarm.io/managed-by: cluster
  name: quentin1ove-default-apps
  namespace: org-pawel
spec:
  catalog: cluster-test
  config:
    configMap:
      name: quentin1ove-cluster-values
      namespace: org-pawel
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: default-apps-eks
  namespace: org-pawel
  userConfig:
    configMap:
      name: quentin1ove-default-apps-userconfig
      namespace: org-pawel
  version: 0.8.0-6d1f44cbde2f5dcecbdc7912d81dfdd57595e21f
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    giantswarm.io/cluster: quentin1ove
    giantswarm.io/managed-by: cluster
  name: quentin1ove-ingress-nginx
  namespace: org-pawel
spec:
  catalog: giantswarm
  config:
    configMap:
      name: quentin1ove-cluster-values
      namespace: org-pawel
  kubeConfig:
    context:
      name: quentin1ove-admin@quentin1ove
    inCluster: false
    secret:
      name: quentin1ove-kubeconfig
      namespace: org-pawel
  name: ingress-nginx
  namespace: kube-system
  version: 3.6.0
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    giantswarm.io/cluster: quentin1ove
    giantswarm.io/managed-by: cluster
  name: quentin1ove-prometheus-blackbox-exporter
  namespace: org-pawel
spec:
  catalog: default
  config:
    configMap:
      name: quentin1ove-cluster-values
      namespace: org-pawel
  kubeConfig:
    context:
      name: quentin1ove-admin@quentin1ove
    inCluster: false
    secret:
      name: quentin1ove-kubeconfig
      namespace: org-pawel
  name: prometheus-blackbox-exporter
  namespace: kube-system
  version: 0.4.1
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    giantswarm.io/cluster: quentin1ove
  name: quentin1ove-ingress-sla-userconfig
  namespace: org-pawel
data:
  values: |
    global:
      ingressSLA:
        checks:
          - ingressClass: nginx
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    giantswarm.io/cluster: quentin1ove
    giantswarm.io/managed-by: cluster
  name: quentin1ove-ingress-sla
  namespace: org-pawel
spec:
  catalog: giantswarm
  config:
    configMap:
      name: quentin1ove-cluster-values
      namespace: org-pawel
  userConfig:
    configMap:
      name: quentin1ove-ingress-sla-userconfig
      namespace: org-pawel
  kubeConfig:
    context:
      name: quentin1ove-admin@quentin1ove
    inCluster: false
    secret:
      name: quentin1ove-kubeconfig
      namespace: org-pawel
  name: ingress-sla
  namespace: kube-system
  version: 0.2.0
```
