### ISSUE TITLE
Support Audit Logging export in teleport

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#3250]
**Is your feature request related to a problem? Please describe.**

Teleport provide audit logs when we access clusters and nodes using teleport but those logs are stored in dynamodb. @ssyno talked to me about this plugin that could be useful https://goteleport.com/docs/reference/helm-reference/teleport-plugin-event-handler/

**Describe the solution you'd like**

I would like to have a solution to be able to get the teleport audit logs sent to customer endpoints.

To that end, we could use this https://goteleport.com/docs/reference/helm-reference/teleport-plugin-event-handler/ with a custom fluentd/fluent bit instance or maybe another teleport plugin to be able to send the logs to customer endpoints if they require it

**Describe alternatives you've considered**

**Additional context**

This is needed by a few customers

cc @gawertm as PO of bigmac. Should we schedule a session to talk about this ?

**Comment by ssyno** [comment]
As of teleport [documentation](https://goteleport.com/docs/management/export-audit-events/fluentd/) around teleport-plugin-event-handler.
1. Generate a plugin configuration `teleport-event-handler-client-tls`
```bash
TELEPORT_CLUSTER_ADDRESS=teleport.giantswarm.io:443
docker run -v `pwd`:/opt/teleport-plugin -w /opt/teleport-plugin public.ecr.aws/gravitational/teleport-plugin-event-handler:15.0.2 configure . ${TELEPORT_CLUSTER_ADDRESS?}
kubectl create secret generic teleport-event-handler-client-tls --from-file=ca.crt=ca.crt,client.crt=client.crt,client.key=client.key
```

 2. It is possible to create separate user and role for each cluster in the following pattern:

```yaml
kind: role
metadata:
  name: teleport-event-handler-gaggle
spec:
  allow:
    rules:
      - resources: ['event', 'session']
        verbs: ['list','read']
        where: 'contains(session.cluster_name, "gaggle")'
version: v5
---
kind: user
metadata:
  name: teleport-event-handler-gaggle
spec:
  roles: ['teleport-event-handler-gaggle']
version: v2
```
Apply with `tctl` command (can be included to our Gitops approach).
```bash
tctl create -f teleport-event-handler-gaggle-role.yaml
```
3. Create teleport-event-handler credentials for each user/role:

```yaml
kind: role
version: v5
metadata:
  name: teleport-event-handler-gaggle-impersonator
spec:
  options:
    max_session_ttl: 10h
  allow:
    impersonate:
      users: ["teleport-event-handler-gaggle"]
      roles: ["teleport-event-handler-gaggle"]
```
Apply with `tctl` command (can be included to our Gitops approach).

```bash
tctl create teleport-event-handler-gaggle-impersonator.yaml
```
4. Both `tbot-credentials` and long `lived-credentials` are supported `to be discussed`
5. `fluentd.conf` has been generated on step no.1,`fluentd deployment?`
6. Implementation of the handler and all mentioned above to teleport helm chart like:
```yaml
eventHandler:
  storagePath: "./storage"
  timeout: "10s"
  batch: 20
  namespace: "teleport"

teleport:
  address: "teleport.giantswarm.io:443"
  identitySecretName: teleport-event-handler-gaggle-identity
  identitySecretPath: identity

fluentd:
  url: "https://fluentd.fluentd.svc.cluster.local/events.log"
  sessionUrl: "https://fluentd.fluentd.svc.cluster.local/session.log"
  certificate:
    secretName: "teleport-event-handler-client-tls"
    caPath: "ca.crt"
    certPath: "client.crt"
    keyPath: "client.key"

persistentVolumeClaim:
  enabled: true
```
