### ISSUE TITLE
Teleport agent pods should prefer to be schedule on control-plane node

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#3324]
Teleport agent pods are currently scheduled and runs on worker node, since, these are critical containers, we want to ensure these are preferred to be deployed in control plane nodes, and for EKS cluster, it can default to worker nodes.

**Requirements**
- [ ] Add nodeAffinity to `teleport-operator`, `tbot`, `teleport-kube-agent` 
```
spec:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - preference:
        matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
```
