### ISSUE TITLE
CAPA IMDSv2 as default

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3403]
## User Story

As AWS user, i want to elevate the security of my clusters by utilizing the IMDS v2 only service, disabling the v1 as per AWS recmmendations: https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/

In terms of implementation, with v1beta2 types there is the possibility to configure IMDS in the `AWSMachine[template]` as part of `AWSMachineSpec` https://github.com/giantswarm/cluster-api-provider-aws/blob/release-2.3/api/v1beta2/awsmachine_types.go#L56:

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1                                                                                                         
kind: AWSMachineTemplate 
...
spec:
  template:
    spec:
      instanceMetadataOptions:
        httpTokens: required
```

For `AWSMachinePools` we can use the following field as we're using v1beta2 already:

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2                                                                                                         
kind: AWSMachinePool  
  ...                                                                                                              
spec:                                                                                                                                                       
  ...
  awsLaunchTemplate:                                                                                                                                        
    ...
    instanceMetadataOptions:                                                                                                                                
      httpTokens: required                                                                                                                                  
```

## Acceptance Criteria

- [ ] By default CAPA clusters are deployed with  `instanceMetadataOptions: httpTokens: required` setting to utilize the IMDS v2 ONLY
- [ ] CAPA should still support adjusting this setting for migrated clusters or customers explicitly stating the pararell need for v1

## Implementation details

- Implementation info to be filled out by engineer
