### ISSUE TITLE
Add hash to names of `KubeadmConfig.spec.files`-referenced secrets

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#3414]
CAPA and other `<Infra>MachinePool` implementations don't watch secrets and therefore we should add a hash of the content to the name if we expect that nodes should roll once the content changes. For example, the containerd config is defined like as follows in the `cluster` chart at the moment, and therefore nodes don't roll automatically:

```
{{- define "cluster.internal.kubeadm.files.cri" }}
- path: /etc/containerd/config.toml
  permissions: "0644"
  contentFrom:
    secret:
      name: {{ include "cluster.resource.name" $ }}-registry-configuration {{/* TODO: rename *-registry-configuration to -containerd-configuration */}}
      key: registry-config.toml {{/* TODO: rename *-registry-config.toml to -containerd-config.toml */}}
{{- end }}
```

[Chat for reference](https://gigantic.slack.com/archives/C01F7T2MNRL/p1713454833692029?thread_ts=1713360280.209569&cid=C01F7T2MNRL)
