### ISSUE TITLE
Can we improve containerd Helm values in cluster chart and how much time would it take?

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#3491]
This existing API is not really good, it's a bit hard to expand it now with local registry mirrors (will add more details from Slack thread).

```
global:
  components:
    containerd:
      containerRegistries: {}
```

The issue happens with `containerRegistries` value, so maybe instead of introducing a breaking change here, we could deprecate the old `containerRegistries` value and add a new one called just `registries`.

So this would be the new API:

```
global:
  components:
    containerd:
      registries: {}
```

And a cluster would use either new improved `registries` API (if it is set) or old `containerRegistries` (if new `registries` API is not set).

Naming this new Helm value `registries` is just an example. We should check the structure of containerd configuration file and then design an API nicely aligned with containerd config, so when you see containerd Helm values you can easily tell where and how those are used in containerd config file.
