### ISSUE TITLE
Enable Loki bloom filters

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3563]
### Motivation

We currently have quite poor query performance, Loki bloom filters might drastically help us here.

### Todo

*   Investigate about Loki bloom filters 
*   Finetune it - be careful! 

### Outcome 

*   We have significantly better query performance on loki

**Comment by QuentinBisson** [comment]
Testing on grizzly:

```yaml
data:
  values: |
    loki:
      loki:
        bloom_compactor: 
          enabled: true
        bloom_gateway: 
          enabled: true
```
