### ISSUE TITLE
Create transit gateway composition

### ISSUE THREAD

**Issue by mproffitt** [giantswarm/roadmap#3596]
It has been identified that there is the need for a transit gateway between the management cluster VPC and infrastructure VPCs

This needs to be added as a new composition that can be nested inside the VPC composition to create a transit gateway that can optionally connect between transit gateways to enable hub-spoke models.

**Comment by mproffitt** [comment]
The main trunk composition is done and partially tested

Still missing:
- TGW peerings - these need to be added in to enable hub/spoke
- Managed Prefix lists - This really wants its own composition but is of less importance right now
- Resource Access Manager - This is required to be able to cut cross account. The stubs are created but hasn't been enabled or tested, potentially needs to be moved into its own composition to be shared with the VPC network

**Comment by mproffitt** [comment]
Transit gateway peering has been added this morning however this requires the transit gateway to be aready connected to a VPC unless an ID is provided (no looking up by name)

In order to achieve true peer to peer transit gateways with name lookup, additional regional discovery needs to be carried out. This is outside of the scope of the network-discovery function which is designed to track VPC networks, not regional or global networks.

I think for the moment this is a fair compromise - to find by name, the TGW must be attached to a VPC, otherwise provide an ID.

The interface then becomes:

```yaml
transitGateways:
  peers:
    name: ""              # required if ID is not provided
    id: ""                # optional, takes precedence over name
    accountId: ""         # falls back to VPC owner ID
    providerConfigRef: {} # Provider Config to use for this TGW 
                          # - falls back to parent
```
