### ISSUE TITLE
configure the current kratix promise setup to run on `golem`

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#3604]
To make our kratix promises work, we need a few objects to be created in the project namespace first. Stub for them is available here: https://github.com/giantswarm/giantswarm-management-clusters/tree/add-kratix/management-clusters/golem/extras/kratix/platform

## ToDo and why

What's left there to do is:
1. `namespace.yaml` - probably should be replaced with `Organization` or left out of scope for "a customer" to create first. For the demo, I think we should create it.
2. `crb_promises_role_binding.yaml` - figure out a `(Cluster)Role` we should use for it in the binding. Currently, the only needed permission is to read Secrets and CMs in the same namespace.
3. [destination_mc.yaml](https://github.com/giantswarm/giantswarm-management-clusters/blob/add-kratix/management-clusters/golem/extras/kratix/platform/destination_mc.yaml) and [gitstatestore_gitops.yaml](https://github.com/giantswarm/giantswarm-management-clusters/blob/add-kratix/management-clusters/golem/extras/kratix/platform/gitstatestore_gitops.yaml) - this drives where Kratix will put rendered files in the gitops repo. 
  3.1. `GitStateStore` needs access to the gitops repo, so the same repo as flux. It should be also possible to reference the same access token that flux is using. 
  3.2. `Destination` - docs are [here](https://docs.kratix.io/main/reference/destinations/intro), we need to inject it in the correct place in the gitops repo directories.
4. `secret_ghcr_pull_token.yaml` - we need to generate a github token to use here (only classic tokens are available) and encrypt with sops
5. `secret_github_token_repo_create.yaml` - we need to create a token that can read template repos and create new ones.

## Bonus

We can probably abstract the role binding and the info config map into something like a `Project` promise, but to get started I skipped it.

**Comment by uvegla** [comment]
# Summary

This is a summary of how it was wired together on `golem` with issues bumped into along the way with their solutions and long term / making it production ready implications. 

## Setup

Dev platform: https://github.com/giantswarm/dev-platform-kratix-promises
GS side gitops: https://github.com/giantswarm/kratix-gitops/
Demo side gitops: https://github.com/DemoTechInc/demotech-gitops

The GS gitops was moved to a separate repo and thus `flux-giantswarm` ns based source and kustomization to avoid breaking or blocking the core ones with the continuous experimentation. See: https://github.com/giantswarm/kratix-gitops/blob/aa9b0997109e8a56025fc119ebd68b9d32985fbf/management-clusters/golem/flux.yaml

The demo related sources and kustomizations are in. the `default` namespace to simulate real scenario: https://github.com/DemoTechInc/demotech-gitops/blob/a0ea4be15bb2fa24e0caee945043f9cdd89e22b9/management-clusters/golem/gitrepo.yaml + https://github.com/DemoTechInc/demotech-gitops/blob/a0ea4be15bb2fa24e0caee945043f9cdd89e22b9/management-clusters/golem/golem.yaml

## Encountered issues

### Password protected SSH keys

Using SSH deploy key for the Kratix destination repo with `write access` enabled is required. It seem at the time of the experiment, Kratix does not support password protected SSH key, so it must be created without / with empty one.

Related parts:
- https://github.com/DemoTechInc/demotech-gitops/blob/a0ea4be15bb2fa24e0caee945043f9cdd89e22b9/management-clusters/golem/secrets/demotech-gitops-kratix-write.enc.yaml
- https://github.com/DemoTechInc/demotech-gitops/blob/a0ea4be15bb2fa24e0caee945043f9cdd89e22b9/management-clusters/golem/kratix/gitstatestore.yaml#L11-L13

...

**Comment by uvegla** [comment]
FTR the resources used for testing

```yaml
apiVersion: promise.platform.giantswarm.io/v1beta1
kind: githubrepo
metadata:
  labels:
    kratix.io/promise-name: githubrepo
  name: laszlo-kratix-2
  namespace: org-kratix-demo
spec:
  githubTokenSecretRef:
    name: dev-platform-gh-access
  registryInfoConfigMapRef:
    name: github-oci-registry-info
  repository:
    description: My first kratix project
    name: laszlo-kratix-2
    owner: DemoTechInc
    templateSource: giantswarm/devplatform-template-go-service
    visibility: private
```

and:

```yaml
apiVersion: promise.platform.giantswarm.io/v1beta1
kind: appdeployment
metadata:
  labels:
    kratix.io/promise-name: appdeployment
  name: laszlo-kratix-2
  namespace: org-kratix-demo
spec:
  interval: 1m
  statusConfigMapReference:
    name: laszlo-kratix-2-info
  suspend: false
  timeout: 3m
  values:
    autoscaling:
      enabled: false
    ingress:
      enabled: false
    monitoring:
      serviceMonitor:
        enabled: false
    pdb:
      enabled: false
  version: '>=0.1.0'
```
