### ISSUE TITLE
e2e tests for capa/capv hybrid env

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#3619]
We want e2e tests for the capa/capv hybrid environment.
Furthermore, working on them is a good test driven way of working on the product itself so let's start here.

- [x] add context
- [x] make cluster standup work
- [x] make cluster teardown work
- [x] add test suite
- [x] ensure all tests pass

**Comment by anvddriesch** [comment]
I made a local new context for cluster standup/teardown which deploys capv to private capa.
After fixing some crd issues cluster creation is now working as expected. However, due to https://github.com/giantswarm/roadmap/issues/3587 it gets stuck as expected

```
    conditions:
    - lastTransitionTime: "2024-07-31T12:38:58Z"
      message: 'failed to create vCenter session: failed to create client: Post "https://...":
        Forbidden'
      reason: VCenterUnreachable
      severity: Error
      status: "False"
      type: Ready
    - lastTransitionTime: "2024-07-31T12:38:58Z"
      message: 'failed to create vCenter session: failed to create client: Post "https://...":
        Forbidden'
      reason: VCenterUnreachable
      severity: Error
      status: "False"
      type: VCenterAvailable
```
