### ISSUE TITLE
ESO kubernetes secret store for default + org-* namespaces

### ISSUE THREAD

**Issue by mproffitt** [giantswarm/roadmap#3623]
As part of the IdP demo, it has been identified that it would be useful to have a default `ExternalSecrets` secret store that can access kubernetes secrets in the same namespace as the store.

This can be useful to read secrets generated by crossplane and mutate them into new secrets, or for existing secrets to be updated with new information.

There are a few aspects to this.

- The need to create an SA for ESO to use in the same namespace (could be `automation` sa)

- A role & rolebinding needs to be set up for the SA to access secrets

<details>
<summary>Example role</summary>

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: eso-store-role
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: eso-store-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-store-role
subjects:
- kind: ServiceAccount
  name: eso
  namespace: default
```

</details>

The secret store then looks like the following (example for `default` namespace)

```yaml
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: default
  namespace: default
spec:
  provider:
    kubernetes:
      # with this, the store is able to pull only 
      # from the `default` namespace
      remoteNamespace: default
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: eso
```
