### ISSUE TITLE
Gather analytics of dashboards usage

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#364]
Towards **https://github.com/giantswarm/roadmap/issues/182 Give customers access to Grafana**

### Description

We'd like to know if customers are using Grafana, and if so, how long are they on pages, which pages are they going to. It'd be cool also to have similar data for Giant Swarm employees.

### TODO

- [x] Check if we can use the GA plugin for Grafana to collect usage data
- [x] check Grafana analytics panel plugin
- [x] check other potential sources of data
  - [x] nginx-IC metrics
  - [x] dex metrics
  - [x] Grafana logs
- [x] #380
- [x] #378
- [x] #379
- [x] #381
- [x] #382
- [x] #398
- [x] clean-up _ghost_ (@mig4 was testing analytics plugin stuff there)
- [x] clean-up Google Analytics if not used (@mig4 tell @marians he can delete the properties/sites)
- [x] https://github.com/giantswarm/giantswarm/issues/18571
- [x] #383
- [x] https://github.com/giantswarm/giantswarm/issues/18574
- [x] #446
- [x] #448

**Comment by mig4** [comment]
Hi @marians, Joe mentioned you may have already looked into this? Just picking this up and wanted to check.

**Comment by mig4** [comment]
First thing I came across is [macropower-analytics-panel](https://grafana.com/grafana/plugins/macropower-analytics-panel/), it's not Google, but allows feeding analytics data from Grafana back into Grafana! More privacy friendly, but requires running a service to store the data.

**Comment by mig4** [comment]
OK, I did a rather extensive search and I cannot see an easy/documented/useful way to hook Google Analytics into Grafana. In the end it's all HTML so maybe injecting a `<script>` would somehow be possible, but I'm not sure what context we'd get that way and so if it would be very useful.

BTW most info out there is about feeding data from Google Analytics into Grafana so it can be visualised and analysed there. There is pretty much nothing about analysing Grafana usage. There is [this issue at GitLab](https://gitlab.com/gitlab-com/gl-infra/infrastructure/-/issues/9716) where they looked into that but eventually went a different route (user research, aka talking to SRE team to ask how they use the dashboards, and possibly using logs).

I'm inclined to try this _analytics-panel_ plugin and see how it works first, before getting into hacky solutions.

**Comment by mig4** [comment]
I experimented with the [macropower-analytics-panel](https://grafana.com/grafana/plugins/macropower-analytics-panel/) plugin and here are the results, for reference.

I deployed [the simple backend service](https://github.com/MacroPower/macropower-analytics-panel/tree/master/server) that acts as a receiver for the frontend plugin to send data to and as temporary storage for that data to _ghost_ MC in `grafana-analytics-panel-server` namespace. This is a simple `Deployment` + `Service` + `Ingress` that can be turned into an app.

The `Ingress` hooks into the Grafana subdomain and exposes the service via an additional path and uses URL rewriting so the backend is unaware it's not running under `/`. For ref, this looks like:

<details>
<summary>Ingress definition</summary>

``` yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app: grafana-analytics-panel-server
  name: grafana-analytics-panel-server
  namespace: grafana-analytics-panel-server
spec:
  rules:
  - host: grafana.g...o
    http:
      paths:
        - backend:
            service:
              name: grafana-analytics-panel-server
              port:
                number: 8080
          path: /grafana-analytics-panel-server(/|$)(.*)
          pathType: ImplementationSpecific
```

</details>

Once that's running, we need to configure the frontend. Unfortunately the way it works is that the plugin adds a _panel_ that has to be added to every dashboard that we want to track. But this can be done programmatically if we use Jsonnet to generate/modify the dashboard JSON files.

<details>
<summary>For ref, manual setup</summary>

1. open a dashboard, add a panel

![grafana analytics-panel-config-1 add-panel 2021-07-05--12-24-11](https://user-images.githubusercontent.com/42101611/124467907-65548880-dd90-11eb-85da-f0343b7d1f79.png)

2. configure the endpoint, in case of _ghost_ this is `https://grafana..../grafana-analytics-panel-server/write`

![grafana analytics-panel-config-2 configure-endpoint 2021-07-05--12-26-14](https://user-images.githubusercontent.com/42101611/124467991-7b624900-dd90-11eb-8295-e4155baca4b0.png)

3. panel should now be working (no error)

![grafana analytics-panel-config-3 panel-working 2021-07-05--12-33-08](https://user-images.githubusercontent.com/42101611/124468050-8cab5580-dd90-11eb-8393-73f86e12025e.png)

4. and metrics should start appearing when browsing the metrics endpoint: `https://grafana..../grafana-analytics-panel-server/metrics`

![grafana analytics-panel-config-4 metrics 2021-07-05--12-35-24](https://user-images.githubusercontent.com/42101611/124468071-93d26380-dd90-11eb-9016-bebad37b14ef.png)

</details>
