### ISSUE TITLE
Hide empty fields in App CRs by introducing a new v1alpha2 API version

### ISSUE THREAD

**Issue by rossf7** [giantswarm/roadmap#365]
Business value: Fixes an annoyance with app platform to improve the developer experience. Also simplifies the manifests when managed by GitOps tools.

User value: These empty fields make app platform seem move complex and increase cognitive load.

## Desired State

The minimum YAML for an app CR is very small. Extra fields are optional or boilerplate that can be defaulted.

```yaml
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: keda
  namespace: 2hr7z
spec:
  catalog: giantswarm-playground
  catalogNamespace: default
  kubeConfig:
    inCluster: false
  name: keda
  namespace: default
  version: 0.1.0
```

## Current State

In the App CRD the optional fields are set correctly but in the Go definition we use structs instead of struct pointers.

Theo tried to introduce this in giantswarm/apiextensions#283. It works well but the problem is we need to handle the nil structs and the code changes got big with a high chance we would miss some cases.

Introducing a new v1alpha2 API version with a conversion webhook is a safer way to change this.

```yaml
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: keda
  namespace: 2hr7z
spec:
  catalog: giantswarm-playground
  catalogNamespace: default
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  install: {}
  kubeConfig:
    context:
      name: ""
    inCluster: false
    secret:
      name: ""
      namespace: ""
  name: keda
  namespace: default
  namespaceConfig: {}
  userConfig:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  version: 0.1.0
```

## Other CRD changes

For https://github.com/giantswarm/roadmap/issues/219 we added the new Catalog CRD which is namespace scoped.
It would be good to move these settings to `.spec.catalog` instead of `.spec` to follow our usual approach.

We could make more changes like renaming `.spec.namespace` to `.spec.targetNamespace` but this would make the conversion process more complex.

```yaml
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: keda
  namespace: 2hr7z
spec:
  catalog:
     name: giantswarm-playground
     namespace: default
  kubeConfig:
    inCluster: false
  name: keda
  namespace: default
  version: 0.1.0
```
