### ISSUE TITLE
Align grafana org-based multi-tenancy with loki tenants - Investigation

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3726]
### Motivation 
We already have a cluster-based tenant concept in loki. This is historically grown - but not really aligned with our new grafana organisation-based mutli-tenancy concept. This might lead to some confusion and maintenance issues in the future. Aligning the tenancy concepts would definitely reduce the complexity here. 

### Todo

- [ ] Investigate (PoC) what would change if we align the multi-tenancy concepts of Loki and Grafana
  - Test it out on one installation and see what breaks :) 
  - Make sure we can revert the change back, if too much stuff breaks
- [ ] Document the risks and discuss with the team what approach to take

### Outcome
- We know what's the risk and decide for an approach to align or not align the multi-tenancy of loki and grafana

**Comment by QuentinBisson** [comment]
Currently blocked due to the freeze

**Comment by QuentinBisson** [comment]
Example:
```
apiVersion: monitoring.grafana.com/v1alpha2
kind: PodLogs
metadata:
  name: pod-tenant-id-from-label
spec:
  selector: {}
  namespaceSelector: {}
  relabelings:
  - action: replace
    targetLabel: "__tenant_id__"
    replacement: "giantswarm"
```
