### ISSUE TITLE
Create app for `analytics-panel-server`

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/roadmap#380]
Towards https://github.com/giantswarm/roadmap/issues/364

We need to add the backend that the analytics-panel will send data to.

TODO:
- [x] Create new app for `analytics-panel-server`
- [x] Make sure scraped by Prometheus

**Comment by mig4** [comment]
@QuentinBisson just in case this is useful, this is the `Ingress` definition I created for testing:

``` yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app: grafana-analytics-panel-server
  name: grafana-analytics-panel-server
  namespace: grafana-analytics-panel-server
spec:
  rules:
  - host: grafana.....io
    http:
      paths:
        - backend:
            service:
              name: grafana-analytics-panel-server
              port:
                number: 8080
          path: /grafana-analytics-panel-server(/|$)(.*)
          pathType: ImplementationSpecific
```
