### ISSUE TITLE
PoC of Observability Platform API

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3820]
### Motivation
with https://github.com/giantswarm/roadmap/issues/3783 we found a concept for the Observability API - but now we also have to test that this concept is feasible. For this we can setup the API in one cluster and use it through a Grafana living in another cluster, while using our dex as sso. This will mirror the customer setup and we'll learn how to work with the API.

### Todo

Keep in mind that this is a proof-of-concept - we are not yet interested in the perfect solution, but interested in learning, so fake it until we make it and cut corners where possible. We will have future implementation stories coming up once we proven that the concept works. 

- [x] Setup the Observability Platform API in a Giant Swarm Installation
- [x] Setup a plain Grafana instance in a Giant Swarm workload cluster
- [x] Connect the plain Grafana instance from a workload cluster with the Observability Platform through the API
- [x] Use our own SSO to authenticate the connection like we would do with the sso of a customer

### Outcome
- We have tested the setup and know what's still missing and what we have to do for the implementation

**Comment by QuantumEnigmaa** [comment]
Update concerning the current setup : now the ingresses are defined as such : 
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-giantswarm
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-url: https://oidc.golem.gaws.gigantic.io/oauth2/dex/auth
    nginx.ingress.kubernetes.io/auth-signin: https://oidc.golem.gaws.gigantic.io/oauth2/dex/start?rd=$escaped_request_uri
  labels:
  name: observability-platform-endpoint
  namespace: loki
spec:
  ingressClassName: nginx
  rules:
  - host: observability.golem.gaws.gigantic.io
    http:
      paths:
      - backend:
          service:
            name: loki-gateway
            port:
              number: 80
        path: /loki/api/v1/query
        pathType: ImplementationSpecific
      - backend:
          service:
            name: loki-gateway
            port:
              number: 80
        path: /loki/api/v1/labels
        pathType: ImplementationSpecific
      - backend:
          service:
            name: loki-gateway
            port:
              number: 80
        path: /loki/api/v1/label
        pathType: ImplementationSpecific
      - backend:
          service:
            name: loki-gateway
            port:
              number: 80
        path: /loki/api/v1/query_range
        pathType: ImplementationSpecific
      - backend:
          service:
            name: loki-gateway
            port:
              number: 80
        path: /loki/api/v1/index
        pathType: ImplementationSpecific
      - backend:
          service:
            name: loki-gateway
            port:
              number: 80
        path: /loki/api/v1/series
        pathType: ImplementationSpecific

  tls:
  - hosts:
    - observability.golem.gaws.gigantic.io
    secretName: observability-platform-endpoint-ingress-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-giantswarm
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-url: https://oidc.golem.gaws.gigantic.io/oauth2/dex/auth
    nginx.ingress.kubernetes.io/auth-signin: https://oidc.golem.gaws.gigantic.io/oauth2/dex/start?rd=$escaped_request_uri
  labels:
  name: observability-platform-endpoint
  namespace: mimir
spec:
  ingressClassName: nginx
  rules:
  - host: observability.golem.gaws.gigantic.io
    http:
      paths:
      - backend:
          service:
            name: mimir-gateway
            port:
              number: 80
        path: /prometheus/api/v1/labels
        pathType: ImplementationSpecific
      - backend:
          service:
            name: mimir-gateway
            port:
              number: 80
        path: /prometheus/api/v1/label
        pathType: ImplementationSpecific
      - backend:
          service:
            name: mimir-gateway
            port:
              number: 80
        path: /prometheus/api/v1/rules
        pathType: ImplementationSpecific
      - backend:
          service:
            name: mimir-gateway
            port:
              number: 80
        path: /prometheus/api/v1/query
        pathType: ImplementationSpecific
      - backend:
          service:
            name: mimir-gateway
            port:
              number: 80
        path: /prometheus/api/v1/query_exemplars
        pathType: ImplementationSpecific
      - backend:
          service:
            name: mimir-gateway
            port:
              number: 80
        path: /prometheus/api/v1/status
        pathType: ImplementationSpecific
      - backend:
          service:
            name: mimir-gateway
            port:
              number: 80
        path: /prometheus/api/v1/metadata
        pathType: ImplementationSpecific

  tls:
  - hosts:
    - observability.golem.gaws.gigantic.io
    secretName: observability-platform-endpoint-ingress-cert
```

So each path is hard-coded as discussed in the [investigation issue](https://github.com/giantswarm/roadmap/issues/3783). 

With this setup, I'm still having exactly the same issues described in my previous comment though.
