### ISSUE TITLE
Persist SQLite database in Backstage app

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3875]
Currently we use in-memory databases, which means that data is erased on Pod restarts.

On our journey towards a more robust deployment, we should persist the database to a filesystem on a persistent volume.

The configuration file needs adaptation like this:

```yaml
  database:
    client: better-sqlite3
    connection:
      directory: "/path/to/volume"
```

## To be discussed

- Do we have a unified way to request a persistent volume in all providers, including bare metal?
- What default size should the volume have?
- What is the effect on cost of our deployments?
- Are there alerts in place for a volume reaching its capacity?
- How to resize volumes in production?
