### ISSUE TITLE
Improve defaulting of container registries configuration when deploying in China

### ISSUE THREAD

**Issue by fiunchinho** [giantswarm/roadmap#3887]
When creating clusters in China, we want to use a different container registry than we usually do, to improve connectivity between the registry and china regions.

We have some sensible defaults in our cluster chart for the container registries configuration. But if we want to use our container registry for China, it currently means that we need to pass this value for all clusters that we want to create in China, adding to the complexity. Our customers would have to add the container registry configuration to all their clusters.

This is the default configuration in the cluster chart
```
containerRegistries:
        docker.io:
          - endpoint: registry-1.docker.io
          - endpoint: giantswarm.azurecr.io
        gsoci.azurecr.io:
          - endpoint: gsoci.azurecr.io
```

This is the configuration that we want to apply for clusters in China
```
containerRegistries:
            docker.io:
              - endpoint: giantswarm-registry.cn-shanghai.cr.aliyuncs.com
              - endpoint: gsoci.azurecr.io
            gsoci.azurecr.io:
              - endpoint: giantswarm-registry.cn-shanghai.cr.aliyuncs.com
              - endpoint: gsoci.azurecr.io
```
