### ISSUE TITLE
Evaluate Backstage plugin: Policy Reporter

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3899]
A new Backstage plugin has been added in commit https://github.com/backstage/backstage/commit/24e4086b49659604ddc6a0f2afd49807be96566d

Plugin details:

```yaml
addedDate: '2025-01-31'
author: kyverno
authorUrl: https://github.com/kyverno
category: Observability
description: Integrates Policy Reporter with Backstage to provide a clear and detailed
  view of Policies related to components in Backstage
documentation: https://github.com/kyverno/backstage-policy-reporter-plugin
iconUrl: https://github.com/cncf/artwork/blob/main/projects/kyverno/icon/color/kyverno-icon-color.png?raw=true
npmPackageName: '@kyverno/backstage-plugin-policy-reporter'
title: Policy Reporter

```

Documentation: https://github.com/kyverno/backstage-policy-reporter-plugin
