### ISSUE TITLE
New Backstage plugin: ScaleOps

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3900]
A new Backstage plugin has been added in commit https://github.com/backstage/backstage/commit/4e53472dcfcd8e332eab9a5f02ce5dcfefba3ad8

Plugin details:

```yaml
addedDate: '2024-12-30'
author: terasky.com
authorUrl: https://github.com/terasky-oss
category: Kubernetes
description: View Rightsizing and resource usage data for your Kubernetes workloads
  right from within Backstage!
documentation: https://github.com/TeraSky-OSS/backstage-plugins/tree/main/plugins/scaleops-frontend
iconUrl: https://avatars.githubusercontent.com/u/100293501?s=200&v=4
npmPackageName: '@terasky/backstage-plugin-scaleops-frontend'
title: ScaleOps

```

Documentation: https://github.com/TeraSky-OSS/backstage-plugins/tree/main/plugins/scaleops-frontend
