### ISSUE TITLE
New Backstage plugin: Policy Reporter

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3901]
A new Backstage plugin has been added in commit https://github.com/backstage/backstage/commit/7df4e2b35f825fa0a1fa8c7d15c7083c945e347b

Plugin details:

```yaml
addedDate: '2025-01-31'
author: kyverno
authorUrl: https://github.com/kyverno
category: Observability
description: Integrates Policy Reporter with Backstage to provide a clear and detailed
  view of Policies related to components in Backstage
documentation: https://github.com/kyverno/backstage-policy-reporter-plugin
iconUrl: https://github.com/cncf/artwork/blob/main/projects/kyverno/icon/color/kyverno-icon-color.png?raw=true
npmPackageName: '@kyverno/backstage-plugin-policy-reporter'
title: Policy Reporter

```

Documentation: https://github.com/kyverno/backstage-policy-reporter-plugin
