### ISSUE TITLE
New Backstage plugin: env0

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3902]
A new Backstage plugin has been added in commit https://github.com/backstage/backstage/commit/57a0658a8fbebfe739d667c20665fa244b7d826a

Plugin details:

```yaml
addedDate: '2025-01-15'
author: env0
authorUrl: https://www.env0.com/
category: Infrastructure
description: Use env0 scaffolder actions to deploy and manage your infrastructure
  using env0 directly from Backstage
documentation: https://github.com/env0/env0-backstage-plugin
iconUrl: https://cdn.prod.website-files.com/63df9b273f861215467107c8/668fd303582961e81ef532fc_env0%20logo-dark.svg
npmPackageName: '@env0/backstage-plugin-env0'
title: env0

```

Documentation: https://github.com/env0/env0-backstage-plugin
