### ISSUE TITLE
New Backstage plugin: Crossplane

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3903]
A new Backstage plugin has been added in commit https://github.com/backstage/backstage/commit/b1368e8e8b769de49cbd850e4656d0ee51a76134

Plugin details:

```yaml
addedDate: '2024-12-30'
author: terasky.com
authorUrl: https://github.com/terasky-oss
category: Kubernetes
description: View Crossplane Resources in Backstage.
documentation: https://github.com/TeraSky-OSS/backstage-plugins/tree/main/plugins/crossplane-resources
iconUrl: https://github.com/cncf/artwork/blob/main/projects/crossplane/icon/color/crossplane-icon-color.png?raw=true
npmPackageName: '@terasky/backstage-plugin-crossplane-resources-frontend'
title: Crossplane

```

Documentation: https://github.com/TeraSky-OSS/backstage-plugins/tree/main/plugins/crossplane-resources
