### ISSUE TITLE
New Backstage plugin: Cyclops Modules

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3904]
A new Backstage plugin has been added in commit https://github.com/backstage/backstage/commit/b1368e8e8b769de49cbd850e4656d0ee51a76134

Plugin details:

```yaml
addedDate: '2024-01-02'
author: Cyclops UI
authorUrl: https://cyclops-ui.com/
category: App Delivery
description: Manage Cyclops Modules through Backstage catalog
documentation: https://github.com/cyclops-ui/backstage-plugins#readme
iconUrl: /img/cyclops.svg
npmPackageName: '@cyclopsui/backstage-plugin-cyclops-modules'
tags:
- Kubernetes
- Productivity
- Delivery
title: Cyclops Modules

```

Documentation: https://github.com/cyclops-ui/backstage-plugins#readme
