### ISSUE TITLE
New Backstage plugin: Glean

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3906]
A new Backstage plugin has been added in commit https://github.com/backstage/backstage/commit/b1368e8e8b769de49cbd850e4656d0ee51a76134

Plugin details:

```yaml
addedDate: '2024-12-30'
author: Mark Shields
authorUrl: https://github.com/beejiujitsu
category: Search
description: Index Backstage TechDocs-enabled Entities into Glean, the AI-powered
  work assistant
documentation: https://github.com/beejiujitsu/wealthsimple-backstage-plugins/tree/master/plugins/glean-backend
iconUrl: /img/glean-logo-circular-white.png
npmPackageName: '@beejiujitsu/backstage-plugin-glean-backend'
title: Glean

```

Documentation: https://github.com/beejiujitsu/wealthsimple-backstage-plugins/tree/master/plugins/glean-backend
