### ISSUE TITLE
New Backstage plugin: Jaeger Tracing

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3907]
A new Backstage plugin has been added in commit https://github.com/backstage/backstage/commit/b1368e8e8b769de49cbd850e4656d0ee51a76134

Plugin details:

```yaml
addedDate: '2024-12-21'
author: Deepankumar
authorUrl: https://github.com/deepan10
category: Observability
description: View Jaeger traces and trace details in Backstage components.
documentation: https://github.com/backstage/community-plugins/blob/main/workspaces/jaeger/plugins/jaeger/README.md
iconUrl: https://avatars.githubusercontent.com/u/28545596?s=200&v=4
npmPackageName: '@backstage-community/plugin-jaeger'
tags:
- monitoring
- tracing
- observability
title: Jaeger Tracing

```

Documentation: https://github.com/backstage/community-plugins/blob/main/workspaces/jaeger/plugins/jaeger/README.md
