### ISSUE TITLE
New Backstage plugin: Knative Event Mesh

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3908]
A new Backstage plugin has been added in commit https://github.com/backstage/backstage/commit/b1368e8e8b769de49cbd850e4656d0ee51a76134

Plugin details:

```yaml
addedDate: '2024-12-16'
author: Knative Community
authorUrl: https://github.com/knative-extensions/backstage-plugins
category: Monitoring
description: A plugin that provides a way to view and manage Knative Event Mesh resources.
documentation: https://knative.dev/docs/install/installing-backstage-plugins/
iconUrl: https://raw.githubusercontent.com/knative/community/refs/heads/main/icons/logo.svg
npmPackageName: '@knative-extensions/plugin-knative-event-mesh-backend'
title: Knative Event Mesh

```

Documentation: https://knative.dev/docs/install/installing-backstage-plugins/
