### ISSUE TITLE
New Backstage plugin: Kubernetes Ingestor

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3909]
A new Backstage plugin has been added in commit https://github.com/backstage/backstage/commit/b1368e8e8b769de49cbd850e4656d0ee51a76134

Plugin details:

```yaml
addedDate: '2024-12-30'
author: terasky.com
authorUrl: https://github.com/terasky-oss
category: Kubernetes
description: Automatically Ingest Kubernetes Workloads and Crossplane Claims as Components,
  and XRDs as Templates.
documentation: https://github.com/TeraSky-OSS/backstage-plugins/tree/main/plugins/kubernetes-ingestor
iconUrl: https://avatars.githubusercontent.com/u/13629408
npmPackageName: '@terasky/backstage-plugin-kubernetes-ingestor'
title: Kubernetes Ingestor

```

Documentation: https://github.com/TeraSky-OSS/backstage-plugins/tree/main/plugins/kubernetes-ingestor
