### ISSUE TITLE
New Backstage plugin: Kyverno Policy Reports

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3910]
A new Backstage plugin has been added in commit https://github.com/backstage/backstage/commit/b1368e8e8b769de49cbd850e4656d0ee51a76134

Plugin details:

```yaml
addedDate: '2025-01-05'
author: terasky.com
authorUrl: https://github.com/terasky-oss
category: Kubernetes
description: View Kyverno Policy reports for Kubernetes resources related to components
  in Backstage.
documentation: https://github.com/TeraSky-OSS/backstage-plugins/tree/main/plugins/kyverno-policy-reports
iconUrl: https://github.com/cncf/artwork/blob/main/projects/kyverno/icon/color/kyverno-icon-color.png?raw=true
npmPackageName: '@terasky/backstage-plugin-kyverno-policy-reports'
title: Kyverno Policy Reports

```

Documentation: https://github.com/TeraSky-OSS/backstage-plugins/tree/main/plugins/kyverno-policy-reports
