### ISSUE TITLE
New Backstage plugin: Wiz

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3911]
A new Backstage plugin has been added in commit https://github.com/backstage/backstage/commit/b1368e8e8b769de49cbd850e4656d0ee51a76134

Plugin details:

```yaml
addedDate: '2024-10-14'
author: roadie.io
authorUrl: https://github.com/RoadieHQ
category: Monitoring
description: View Wiz issues status in Backstage.
documentation: https://roadie.io/backstage/plugins/wiz/
iconUrl: https://roadie.io/images/wiz-logo.png
npmPackageName: '@roadiehq/backstage-plugin-wiz'
title: Wiz

```

Documentation: https://roadie.io/backstage/plugins/wiz/
