### ISSUE TITLE
New Backstage plugin: DevPod

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3912]
A new Backstage plugin has been added in commit https://github.com/backstage/backstage/commit/1f6f2220781b37bed9c3b9e91e6d9ac6e81e1ea4

Plugin details:

```yaml
addedDate: '2024-12-30'
author: terasky.com
authorUrl: https://github.com/terasky-oss
category: Development
description: Automatically launch fully-contained dev environments with DevPod, directly
  from Backstage!
documentation: https://github.com/TeraSky-OSS/backstage-plugins/tree/main/plugins/devpod-plugin
iconUrl: https://raw.githubusercontent.com/loft-sh/devpod/refs/heads/main/docs/static/media/devpod-logo.png
npmPackageName: '@terasky/backstage-plugin-devpod'
title: DevPod

```

Documentation: https://github.com/TeraSky-OSS/backstage-plugins/tree/main/plugins/devpod-plugin
