### ISSUE TITLE
New Backstage plugin: Kubernetes Ingestor

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3915]
A new Backstage plugin has been added in commit https://github.com/backstage/backstage/commit/8ad47eab469bb0d107f6381c4e087f8e9674504c

Plugin details:

```yaml
addedDate: '2024-12-30'
author: terasky.com
authorUrl: https://github.com/terasky-oss
category: Kubernetes
description: Automatically Ingest Kubernetes Workloads and Crossplane Claims as Components,
  and XRDs as Templates.
documentation: https://github.com/TeraSky-OSS/backstage-plugins/tree/main/plugins/kubernetes-ingestor
iconUrl: https://avatars.githubusercontent.com/u/13629408
npmPackageName: '@terasky/backstage-plugin-kubernetes-ingestor'
title: Kubernetes Ingestor

```

Documentation: https://github.com/TeraSky-OSS/backstage-plugins/tree/main/plugins/kubernetes-ingestor
