### ISSUE TITLE
New Backstage plugin: Kyverno Policy Reports

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3916]
A new Backstage plugin has been added in commit https://github.com/backstage/backstage/commit/fb4a376e689afe635080c0e43bfc4d31dc646ffa

Plugin details:

```yaml
addedDate: '2025-01-05'
author: terasky.com
authorUrl: https://github.com/terasky-oss
category: Kubernetes
description: View Kyverno Policy reports for Kubernetes resources related to components
  in Backstage.
documentation: https://github.com/TeraSky-OSS/backstage-plugins/tree/main/plugins/kyverno-policy-reports
iconUrl: https://github.com/cncf/artwork/blob/main/projects/kyverno/icon/color/kyverno-icon-color.png?raw=true
npmPackageName: '@terasky/backstage-plugin-kyverno-policy-reports'
title: Kyverno Policy Reports

```

Documentation: https://github.com/TeraSky-OSS/backstage-plugins/tree/main/plugins/kyverno-policy-reports
