### ISSUE TITLE
New Backstage plugin: Facets.cloud Platform

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3933]
A new Backstage plugin has been added in commit https://github.com/backstage/backstage/commit/c2ff31f64f864ab146f8ca7fd025561c3073cc89

Plugin details:

```yaml
addedDate: '2025-02-25'
author: Facets.cloud
authorUrl: https://facets.cloud
category: Deployment
description: 'Show environments, releases and terraform outputs deployed by Facets.cloud
  Platform.

  Plugin includes an Environment Overview, Release Details and Terraform Output ComponentCard.

  '
documentation: https://github.com/Facets-cloud/facets-backstage-plugin
iconUrl: /img/facets-cloud-logo.png
npmPackageName: '@facets-cloud/backstage-plugin'
title: Facets.cloud Platform

```

Documentation: https://github.com/Facets-cloud/facets-backstage-plugin
