### ISSUE TITLE
New Backstage plugin: Renovate Hoster

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3966]
A new Backstage plugin has been added in commit https://github.com/backstage/backstage/commit/55f0aed0f6fb3f491ce0babdbd7aa93cc694b824

Plugin details:

```yaml
addedDate: '2025-03-31'
author: secustor
authorUrl: https://github.com/secustor
category: Quality
description: This plugin enables you to host Renovate CLI yourself inside of Backstage
  and extract data from it.
documentation: https://github.com/secustor/backstage-plugins/tree/main/plugins/renovate
npmPackageName: '@backstage/backstage-plugin-renovate'
title: Renovate Hoster

```

Documentation: https://github.com/secustor/backstage-plugins/tree/main/plugins/renovate
