### ISSUE TITLE
New Backstage plugin: Amplication Resources

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3968]
A new Backstage plugin has been added in commit https://github.com/backstage/backstage/commit/090553e95bbefa2bb63988d2705150b669157582

Plugin details:

```yaml
addedDate: '2025-03-07'
author: Amplication
authorUrl: https://amplication.com
category: Development
description: A plugin that integrates Amplication services into Backstage, enabling
  seamless development and management of your applications.
documentation: https://docs.amplication.com/day-zero/integrate-with-backstage
iconUrl: /img/amplication_logo.png
npmPackageName: '@backstage-community/plugin-scaffolder-backend-module-amplication'
title: Amplication Resources

```

Documentation: https://docs.amplication.com/day-zero/integrate-with-backstage
