### ISSUE TITLE
CAPI EKS GAP Analysis

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#434]
CAPI EKS GAP Analysis

**Comment by anvddriesch** [comment]
Update on China:
- ControlPlane creation works. 
- However we have to use the `AWSClusterControllerIdentity` instead of the `AWSClusterRoleIdentity'. We try to find out why.
- The controller tried to use the AZ `cn-north-1d` which did not really work.
- See here for what had to be added in the spec to make the creation work:
```
  identityRef:
    kind: AWSClusterControllerIdentity
    name: default
  networkSpec:
    vpc:
      availabilityZoneUsageLimit: 2
      availabilityZoneSelection: Ordered
```
- MachinePool creation fails right now.
- The reason is that the automatic role creation does not work for china (wrong domain in code)
- We can add this to the `capa-iam-controller`
