### ISSUE TITLE
Add our default "GS PSP" to the `apptestctl` tool.

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#482]

**Comment by ubergesundheit** [comment]
PSPs are defined here https://github.com/giantswarm/k8scloudconfig/blob/master/files/k8s-resource/psp_policies.yaml

For `kind` clusters, it is required to align kubelet flags to https://github.com/giantswarm/k8scloudconfig/blob/master/files/manifests/k8s-api-server.yaml#L42
```
--enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,DefaultStorageClass,PersistentVolumeClaimResize,PodSecurityPolicy,Priority,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
```

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
        extraArgs:
          enable-admission-plugins: NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,DefaultStorageClass,PersistentVolumeClaimResize,PodSecurityPolicy,Priority,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
```
