### ISSUE TITLE
Provide customers with the access to Prometheus metrics on the management cluster

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#496]
## User Story

_- As a customer, I want to access Prometheus metrics on the management cluster so that I can build dashboards and alerting on my side to make sure the apps I use work correctly._

## Description

Customers are using Flux on the MC to manage workload clusters in gitops way. In. the future they might use more apps. They want to monitor flux application status and whether are configurations are applied correctly. Not the flux application itself, it’s the sync / whether that’s correct.

We can implement `federation`, `remote read`, or `remote write` and provide a PromQL endpoint.

The `remote write` solution is easily extensible to workload clusters. It also covers the ***#402 Allow customers to query data / provide Promql Endpoint*** story.
Cortex and community in general use `remote write`.

We can also move ourselves to 'Remote Write' to write to Grafana Cloud. This way we will make sure it is maintained #dogfooding.

## TODO

- [x] #1109
- [x] #1110
- [x] #1111
- [x] #1167
- [x] #1140
- [x] #1143
- [x] #1169
- [x] #1175
- [x] Make sure customer is using newer Prometheus (where `remote write` is supported)
- [x] Cleaning up our own GS remote write config
- [x] #1238
- ~[ ] Do we need an implementation in the UI (web ui/ cli)~ not needed for now

**Comment by snizhana-dynnyk** [comment]
ping @JosephSalisbury

**Comment by JosephSalisbury** [comment]
See https://docs.google.com/presentation/d/1v585vtZGiCU0RSeWU8iuUismzGMs_5_cQaBBQgsPrIQ/edit?usp=sharing for deck for chatting with folks

**Comment by JosephSalisbury** [comment]
Note: If users are using VictoriaMetrics as a target for remote write, they can use `vmalert` to provide alerting on those metrics (similar to cortex / thanos rulers)

**Comment by weatherhog** [comment]
- design a CR for remote write - reuse what is available upstream
- each CR has a 1 to 1 relationship with the target
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write

**Comment by JosephSalisbury** [comment]
```
apiVersion: giantswarm/monitoring/v1beta1?????    # Theo and or Quentin and or Hervé work this out because I'm dumb
kind: RemoteWrite
metadata:
  name: adidas-victoria-metrics 
spec:
  clusterSelector:  # Labels on Cluster CR to select
    odp/cluster: pap01
  remoteWrite:  # Note: use prometheus/prometheus/config#RemoteWriteConfig for this
    url: https://foobar.com
    write_relabel_configs:
    - foobar
```
