### ISSUE TITLE
Offer description for pre-defined roles

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#602]
An admin gets very little information on the roles (when we say "role" here we mean: `Role`, `ClusterRole`) offered in the access control UI:

- Name of the role
- Whether it is a ClusterRole or Role
- Managed by Giant Swarm

Even with carefully chosen names, some questions are open:

- What's the purpose of the role?
- Will Giant Swarm adapt the permissions of this role in the future?
- Can this role be bound on a cluster level, or on a namespace level, or both?

## Suggestion

We could introduce a description annotation to apply on all pre-defined roles, which then gets displayed in the access control UI if set.

Example

```yaml
  metadata:
    annotations:
      ui.giantswarm.io/description: Includes all permissions needed to browse resources in the web UI. Will be updated by Giant Swarm.
```

Of course customers would be free to use that annotation, too, in order to provide descriptions for their own roles.
