### ISSUE TITLE
Improve how we consume, deploy and upgrade CAPI CRDs

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#671]
During our ongoing effort to deploy and use the latest Cluster API controllers (CAPI, CAPA, CAPZ, CAPO), we have discovered a multitude of hurdles along the way, related to how we are consuming, deploying and upgrading CAPI types (CRDs and Go types) and manifests (Deployment, webhook, RBAC, etc).

## What are those issues?

Let's outline some of the concrete issues.

### CAPI CRD manifests stored in `apiextensions` repo

All CRD manifests are currently kept in [`apiextensions` helm directory](https://github.com/giantswarm/apiextensions/tree/master/helm). While the current state, where the CRD files are broken down per CRD, is better than the previous state, where all CRDs were in a big single file, it is still hard to review changes when we are upgrading those CRDs and the upgrade is adding new API version. Here are 2 PRs that show that:
- https://github.com/giantswarm/apiextensions/pull/855
- https://github.com/giantswarm/apiextensions/pull/848

### CAPI CRD manifests deployed with `opsctl`

When we want to deploy these CRDs, we do that by running `opsctl ensure crds` command. This is an imperative approach, there is no way to determine why is some CRD deployed to some management cluster, or even to be sure that it was deployed by `opsctl ensure crds` command.

### Consuming Go types from upstream projects gets broken

Last year we had a problem related to Go dependencies in our projects, where we could not upgrade k8s Go modules in our projects because Cluster API projects used older incompatible versions of those k8s modules. We formed a working group to get around this problem. The solution was to fork Cluster API, upgrade k8s modules, and use and maintain that fork as long as it's necessary. Keeping forks up-to-date was manual, time-consuming and very tedious chore.

Recently we have seen that CAPA maintainers have decided that CAPA project should not be consumed as a Go library. Using latest CAPA and CAPI (in our last tests) is currently broken (go build does not work), since CAPA is referencing specific commit from CAPI, and not a released version.

## How to make this better?

We need a new way to:
- Consume CAPI CRD Go types
- Consume CAPI CRDs manifests
- Deploy CAPI CRDs
- Upgrade CAPI CRDs

### Fully generated CAPI Go types and CRDs

Here are few things that I have been working on last and this week:

- [`giantswarm/cluster-api-gen`](https://github.com/giantswarm/cluster-api-gen/tree/init-v0.3.x): copy of a subset of Cluster API project, created with code generation. It contains:
  - Cluster API `api` subpackage with all types
  - CRD manifests, generated in `config/crd` directory
  - CRD manifests broken into bases and patches per CRD and per API version to make reviewing easier (new API version just adds new files, changes in existing API version are reviewed in smaller existing files).
  - We specify other CRD patches (like webhooks and certs) also in YAML in a declarative way.
  - The resulting CRDs can be easily packaged and attached to a release manifest (like in upstream).
  - I propose versioning it with `vA.B.X+A.B.Y` (e.g. `v0.3.1+0.3.24`), where `vA.B.X` is the version of generated project and `A.B.Y` is semver build info which specifies from which upstream version it got generated, where we keep `vA.B` identical.
  - It is very easy to get new CAPI versions, everything in the project is auto-generated.

- [`giantswarm/apigen`](https://github.com/giantswarm/apigen/tree/init): Go tool that is generating Go code for the above `giantswarm/cluster-api-gen` project. What it does:
  - It copies `api` subpackage from an upstream CAPI project. (still missing copying of other directories, e.g. `controlplane/kubeadm/api`).
  - Then it parses Go files with `parser` package to get all dependencies/packages used in those files
  - For local CAPI packages from the same project, it copes their corresponding directories Go files
  - For external packages, it updates `go.mod` file
  - Resulting Go project (`giantswarm/cluster-api-gen`) can be built and used out of the box.
  - Resulting Go project (`giantswarm/cluster-api-gen`) has smaller dependency tree than original upstream project.
  - It is easy to implement that we can override versions of some dependencies in the resulting Go project.
  - Resulting Go project can be modified and extended.
  - It is very easy to get new CAPI versions.
  - It can be used for all CAPI projects, including provider-specific ones.
  - Projects can use pre-generated `giantswarm/cluster-api-gen` or use `apigen` directly and generate CAPI API types locally.

In a similar fashion we can get:
- `giantswarm/cluster-api-provider-aws-gen`
- `giantswarm/cluster-api-provider-azure-gen`
- `giantswarm/cluster-api-provider-openstack-gen`

Now how to deploy this?

### crd-operator

We are using operator to manage so many things, so I am proposing to also manage CRDs with an operator.

It is currently not straightforward to deploy CRDs with Helm, but we can do something else, we can deploy a CR that specifies which CRD we want, let's call it `CRDRelease` for example.

It specifies the following:
- Where is the CRD
  - Which repo
  - Which release in that repo
  - Which release asset contains this CRD (this release asset can have other CRDs as well, this CRDRelease will take just one it needs, by its name)
- How to upgrade the CRD
  - Option to scale down some consumer apps before upgrading CRDs (upstream `clusterctl` scales down controllers before performing an upgrade)
  - Specification of the expected CRD patch, i.e. what is different in this new CRD when compared to the existing one. This is a fail safe. If this check fails, the CRD upgrade (and entire App upgrade) is not done. This way we can prevent unexpected issues. In the below example we add v1alpha3 API version, so v1alpha2 is not a stored version anymore.

**The `CRDRelease` CR is deployed with Helm from the appropriate app repo. This way we upgrade controllers and their CRDs together, both in a declarative way, both using the same deployment pipeline, we can exactly see which CRDs are deployed when, from where and to which management cluster, and we have a fail safe to protect us from unexpected CRD changes.**

Alternatively to building a new `crd-operator` operator, we can reference `CRDRelease` CR from `App` CR and implement CRD deployment in the `app-operator`.

```
apiVersion: crd.giantswarm.io/v1alpha1
kind: CRDRelease
metadata:
  name: clusters.cluster.x-k8s.io
spec:
  repo: giantswarm/cluster-api-gen
  release: v0.3.2+0.3.24
  asset: infrastructure-components.yaml
  upgradeStrategy:
    scaleDownConsumers: true
    consumers:
    - cluster-api
    - cluster-api-provider-aws
    - prometheus-meta-operator
    - dns-operator-azure
    expectedPatches:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: clusters.cluster.x-k8s.io
      spec:
        versions:
          - name: v1alpha2
            storage: false
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: clusters.cluster.x-k8s.io
      spec:
        versions:
          - additionalPrinterColumns:
              - description: Cluster status such as Pending/Provisioning/Provisioned/Deleting/Failed
                jsonPath: .status.phase
                name: Phase
                type: string
            name: v1alpha3
            # ...
```

This spec is from the top of my head, we can define it together to cover all our needs.
