### ISSUE TITLE
use flatcar as base OS on capo clusters

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#778]
Towards https://github.com/giantswarm/roadmap/issues/426

### User stories
- As a giant swarm customer I want to have a secure and container optimized operating system in my clusters so that I don't need to worry about the performance and security of my Kubernetes  clusters

### TODO

Upstream `qemu` build boot on openstack but doesn't contain the valid kernel parameters to make ignition work. We have to either
* use upstream `image-builder` repository and make a flatcar image for openstack ( image-source: `https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_openstack_image.img.bz2`) or
* patch the already existing `qemu-flatcar` image to make ignition work on openstack

### Tasks

- [x] #780 

#### additional details:

* `flatcar.oem.id` isn't set as kernel argument) `coreos-metadata` service stops and therefore no ignition configuration is being processed
  ```
  coreos-metadata[682]: Caused by: Couldn't find flag 'flatcar.oem.id' or 'coreos.oem.id' in cmdline file (/proc/cmdline)
  ```
* below listed `kubeadmconfigtemplate` (which got generated by CAPI/CAPO) on a local machine works fine

<details>
  <summary>`kubeadmconfigtemplate` flatcar linux</summary>

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: OpenStackMachineTemplate
metadata:
  annotations:
    meta.helm.sh/release-name: galaxy-cluster
    meta.helm.sh/release-namespace: org-giantswarm
  labels:
    app: cluster-openstack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.10.1
    application.giantswarm.io/team: rocket
    cluster.x-k8s.io/cluster-name: galaxy
    giantswarm.io/cluster: galaxy
    giantswarm.io/organization: giantswarm
    helm.sh/chart: cluster-openstack-0.10.1
  name: galaxy-galaxy-flatcar
  namespace: org-giantswarm
  ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      kind: Cluster
      name: galaxy
      uid: dd9f6431-14dd-43f6-8687-257d756b0919
spec:
  template:
    spec:
      cloudName: openstack
      flavor: n1.medium
      identityRef:
        kind: Secret
        name: openstack-cloud-config
      image: "Flatcar Container Linux stable-3139.2.0-kube-v1.21.10-mario"
      rootVolume:
        diskSize: 50
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  annotations:
    meta.helm.sh/release-name: galaxy-cluster
    meta.helm.sh/release-namespace: org-giantswarm
  labels:
    app: cluster-openstack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.10.1
    application.giantswarm.io/team: rocket
    cluster.x-k8s.io/cluster-name: galaxy
    giantswarm.io/cluster: galaxy
    giantswarm.io/organization: giantswarm
    helm.sh/chart: cluster-openstack-0.10.1
  name: galaxy-galaxy-flatcar-lon-1
  namespace: org-giantswarm
  ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      kind: Cluster
      name: galaxy
      uid: dd9f6431-14dd-43f6-8687-257d756b0919
spec:
  clusterName: galaxy
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: galaxy
      cluster.x-k8s.io/deployment-name: galaxy-galaxy-flatcar-lon-1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cluster-openstack
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/version: 0.10.1
        application.giantswarm.io/team: rocket
        cluster.x-k8s.io/cluster-name: galaxy
        cluster.x-k8s.io/deployment-name: galaxy-galaxy-flatcar-lon-1
        giantswarm.io/cluster: galaxy
        giantswarm.io/organization: giantswarm
        helm.sh/chart: cluster-openstack-0.10.1
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: galaxy-galaxy-flatcar-lon-1
      clusterName: galaxy
      failureDomain: gb-lon-1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
        kind: OpenStackMachineTemplate
        name: galaxy-galaxy-flatcar
      version: v1.22.8
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  annotations:
    meta.helm.sh/release-name: galaxy-cluster
    meta.helm.sh/release-namespace: org-giantswarm
  labels:
    app: cluster-openstack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.10.1
    application.giantswarm.io/team: rocket
    cluster.x-k8s.io/cluster-name: galaxy
    giantswarm.io/cluster: galaxy
    giantswarm.io/organization: giantswarm
    helm.sh/chart: cluster-openstack-0.10.1
  name: galaxy-galaxy-flatcar-lon-1
  namespace: org-giantswarm
  ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      kind: Cluster
      name: galaxy
      uid: dd9f6431-14dd-43f6-8687-257d756b0919
spec:
  template:
    spec:
      ignition:
        containerLinuxConfig:
          strict: false
          additionalConfig: |
            storage:
              links:
              # For some reason enabling services via systemd.units doesn't work on Flatcar CAPI AMIs.
              - path: /etc/systemd/system/multi-user.target.wants/coreos-metadata.service
                target: /usr/lib/systemd/system/coreos-metadata.service
              - path: /etc/systemd/system/multi-user.target.wants/kubeadm.service
                target: /etc/systemd/system/kubeadm.service
              files:
                - contents:
                    source: |
                      ssh-ed25519 <content from KubeadmConfigTemplate>
                  path: /etc/ssh/trusted-user-ca-keys.pem
                  permissions: "0600"
                - contents:
                    source: |
                      # Use most defaults for sshd configuration.
                      Subsystem sftp internal-sftp
                      ClientAliveInterval 180
                      UseDNS no
                      UsePAM yes
                      PrintLastLog no # handled by PAM
                      PrintMotd no # handled by PAM
                      # Non defaults (#100)
                      ClientAliveCountMax 2
                      PasswordAuthentication no
                      TrustedUserCAKeys /etc/ssh/trusted-user-ca-keys.pem
                      MaxAuthTries 5
                      LoginGraceTime 60
                      AllowTcpForwarding no
                      AllowAgentForwarding no
                  path: /etc/ssh/sshd_config
                  permission: "0600"
            systemd:
              units:
              - name: kubeadm.service
                dropins:
                - name: 10-flatcar.conf
                  contents: |
                    [Unit]
                    # kubeadm must run after coreos-metadata populated /run/metadata directory.
                    Requires=coreos-metadata.service
                    After=coreos-metadata.service
                    [Service]
                    # Ensure kubeadm service has access to kubeadm binary in /opt/bin on Flatcar.
                    Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/bin
                    # To make metadata environment variables available for pre-kubeadm commands.
                    EnvironmentFile=/run/metadata/*
      preKubeadmCommands:
      - envsubst < /etc/kubeadm.yml > /etc/kubeadm.yml.tmp
      - mv /etc/kubeadm.yml.tmp /etc/kubeadm.yml
      - 'files="/etc/ssh/trusted-user-ca-keys.pem /etc/ssh/sshd_config"; for f in $files; do tmpFile=$(mktemp); cat "${f}" | base64 -d > ${tmpFile}; if [ "$?" -eq 0 ]; then mv ${tmpFile} ${f};fi;  done;'
      - systemctl restart sshd
      format: ignition
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            node-labels: giantswarm.io/node-pool=galaxy-flatcar-lon-1
          name: ${HOSTNAME}
      postKubeadmCommands:
        - systemctl restart sshd
      users:
        - name: giantswarm
          groups: sudo
          sudo: ALL=(ALL) NOPASSWD:ALL
```
</details>
