### ISSUE TITLE
[Spec] Provide default metadata to Helm charts templated by chart-operator.

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#86]
There are use cases when we could use some metadata that tells us we're running in GS environments and need to tune some settings.

Such metadata should be available as helm chart variables set by `[app|chart]-operator`.

Example use case: we have an application with enabled network policies and we want to ensure that the application can access Kue DNS service. Normally the service is available on port 53, yet in GS clusters it's on 1053. This requires enabling both ports in network policy like this:

```yaml
ports:
- protocol: TCP
  port: 53
- protocol: UDP
  port: 53
- protocol: TCP
  port: 1053
- protocol: UDP
  port: 1053
```

If the metadata would be provided, the above can be more strict and rewritten as:

```yaml
ports:
{{ if .Values.ginatswarm }}
- protocol: TCP
  port: 1053
- protocol: UDP
  port: 1053
{{ else }}
- protocol: TCP
  port: 53
- protocol: UDP
  port: 53
{{ end }}
```

Let's discuss what kind of metadata we would like. Later, let's put this into ADR.

Chiara added: Next step after this ticket would possibly be to "Extend chart-operator to inject information (variables) mentioned in this ticket"
